-- Add Onion Boil recipe (French version in recipes table)
INSERT INTO recipes (
  slug,
  title,
  excerpt,
  content,
  introduction,
  conclusion,
  prep_time,
  cook_time,
  rest_time,
  total_time,
  servings,
  servings_unit,
  difficulty,
  ingredients,
  instructions,
  nutrition,
  tags,
  cuisine,
  author,
  seo_title,
  seo_description,
  faq,
  published_at,
  updated_at
) VALUES (
  'bouillon-oignon-reconfortant',
  'Bouillon d''oignon réconfortant – Recette facile pour l''hiver',
  'Cette recette de bouillon d''oignon transforme de simples oignons en un bouillon savoureux et réconfortant, parfait pour les froides soirées d''hiver.',
  'Le bouillon d''oignon est une recette sous-estimée qui se situe entre la soupe à l''oignon et la soupe de légumes. Les oignons mijotent doucement, deviennent fondants et libèrent leur douceur naturelle pour créer un bouillon simple mais profondément savoureux.',
  E'Quand l''hiver s''installe et que tout ce que tu veux, c''est un repas chaud et rassurant, le bouillon d''oignon arrive en héros discret. Ça peut sembler trop simple pour être vrai, mais quelques oignons bien mijotés peuvent faire des miracles.\n\nCette recette de bouillon d''oignon fait tranquillement sa place parmi les meilleurs repas d''hiver. C''est un peu la cousine relaxe de la soupe à l''oignon : moins d''étapes, moins d''ingrédients, mais tout autant de réconfort. Un vrai câlin dans un bol pour les journées froides.',
  E'Servez le bouillon d''oignon bien chaud, dans un grand bol que vous pouvez tenir entre vos mains. C''est parfait comme repas léger, entrée ou souper simple lors des journées glaciales.\n\nAccompagnez-le de pain croustillant ou dégustez-le tel quel comme l''un de ces repas réconfortants d''hiver qui prouvent que la simplicité a toujours bon goût.',
  10,
  40,
  0,
  50,
  4,
  'bols',
  'facile',
  '[{"title": "Ingrédients", "items": [{"quantity": "4", "unit": "gros", "name": "oignons", "note": "pelés et coupés en deux"}, {"quantity": "1.5", "unit": "L", "name": "bouillon de légumes", "note": ""}, {"quantity": "2", "unit": "c. à soupe", "name": "beurre", "note": ""}, {"quantity": "1", "unit": "c. à soupe", "name": "huile d''olive", "note": ""}, {"quantity": "1", "unit": "c. à thé", "name": "poudre d''ail", "note": ""}, {"quantity": "1/2", "unit": "c. à thé", "name": "thym séché", "note": ""}, {"quantity": "", "unit": "", "name": "sel", "note": "au goût"}, {"quantity": "", "unit": "", "name": "poivre noir", "note": "au goût"}]}]',
  '[{"step": 1, "title": "Préparer les oignons", "content": "Pelez les oignons et coupez-les en deux de haut en bas. Les garder en gros morceaux permet qu''ils restent intacts tout en devenant bien fondants à la cuisson.", "tip": "Les oignons jaunes offrent le meilleur équilibre entre douceur et saveur."}, {"step": 2, "title": "Développer la saveur", "content": "Dans une grande casserole, faites fondre le beurre avec l''huile d''olive à feu moyen. Déposez les oignons côté coupé vers le bas et laissez-les légèrement caraméliser.", "tip": "Ne pressez pas cette étape : une légère coloration ajoute beaucoup de goût."}, {"step": 3, "title": "Ajouter le bouillon", "content": "Versez le bouillon de légumes jusqu''à ce que les oignons soient presque couverts. Ajoutez la poudre d''ail, le thym, le sel et le poivre.", "tip": "Le bouillon de poulet fonctionne aussi très bien."}, {"step": 4, "title": "Mijoter doucement", "content": "Portez à légère ébullition, puis réduisez à feu doux. Laissez mijoter à découvert pendant 35 à 40 minutes, jusqu''à ce que les oignons soient très tendres.", "tip": "Plus ça mijote, plus on se rapproche d''une vraie soupe à l''oignon."}, {"step": 5, "title": "Servir", "content": "Goûtez et ajustez l''assaisonnement au besoin. Servez bien chaud avec les oignons fondants et beaucoup de bouillon.", "tip": "Excellent avec du pain grillé ou comme base pour une soupe à l''oignon maison."}]',
  '{"calories": 140, "protein": 3, "carbs": 18, "fat": 6, "fiber": 3, "sugar": 6, "sodium": 520}',
  ARRAY['oignon', 'bouillon d''oignon', 'soupe à l''oignon', 'soupe de légumes', 'repas d''hiver', 'idées repas hiver', 'repas chauds pour journées froides', 'recette réconfortante'],
  'Réconfort',
  'Menucochon',
  'Bouillon d''oignon réconfortant | Recette facile pour l''hiver',
  'Découvrez cette recette de bouillon d''oignon facile et réconfortante, parfaite comme repas d''hiver chaud à base d''oignons et de bouillon savoureux.',
  '[{"question_fr": "Peut-on préparer le bouillon d''oignon à l''avance?", "answer_fr": "Oui, il se conserve très bien et est encore meilleur réchauffé.", "question_en": "Can onion boil be made ahead?", "answer_en": "Yes, it stores well and tastes even better reheated."}, {"question_fr": "Quelle est la différence avec une soupe à l''oignon?", "answer_fr": "Le bouillon d''oignon est plus simple, sans farine ni fromage, mais tout aussi réconfortant.", "question_en": "What is the difference between onion boil and onion soup?", "answer_en": "Onion boil is simpler, without flour or cheese, but just as comforting."}, {"question_fr": "Peut-on ajouter d''autres légumes?", "answer_fr": "Oui, les carottes et le céleri s''y ajoutent très bien.", "question_en": "Can other vegetables be added?", "answer_en": "Yes, carrots and celery work very well."}]',
  NOW(),
  NOW()
);

-- Add English translation
INSERT INTO recipe_translations (
  recipe_id,
  locale,
  slug_en,
  title,
  excerpt,
  content,
  introduction,
  conclusion,
  ingredients,
  instructions,
  seo_title,
  seo_description,
  faq,
  translated_at
)
SELECT
  id,
  'en',
  'onion-boil-recipe',
  'Onion Boil Recipe – Cozy Winter Onion Soup',
  'This comforting onion boil recipe transforms simple onions into a rich, savory broth that feels like a warm hug on cold winter days.',
  'The onion boil is an underrated classic that sits somewhere between onion soup and vegetable soup. As the onions simmer, they soften and release natural sweetness, creating a deeply comforting broth with very little effort.',
  E'When winter hits and all you want is something warm, simple, and soothing, the onion boil quietly steals the show. It may sound humble, but don''t underestimate the power of onions slowly simmered into a fragrant, savory broth.\n\nThis onion boil recipe has been making waves as the ultimate winter comfort food. Think of it as onion soup''s laid-back cousin: fewer steps, fewer ingredients, but all the cozy vibes. It''s the kind of meal that warms your hands, your belly, and your mood all at once.',
  E'Serve this onion boil hot, preferably in a big bowl you can wrap your hands around. It''s perfect as a light dinner, a starter, or even a comforting lunch on cold days.\n\nPair it with crusty bread or enjoy it on its own as one of those warm meals for cold days that proves simple food can still be deeply satisfying.',
  '[{"title": "Ingredients", "items": [{"quantity": "4", "unit": "large", "name": "onions", "note": "peeled and halved"}, {"quantity": "1.5", "unit": "L", "name": "vegetable broth", "note": ""}, {"quantity": "2", "unit": "tbsp", "name": "butter", "note": ""}, {"quantity": "1", "unit": "tbsp", "name": "olive oil", "note": ""}, {"quantity": "1", "unit": "tsp", "name": "garlic powder", "note": ""}, {"quantity": "1/2", "unit": "tsp", "name": "dried thyme", "note": ""}, {"quantity": "", "unit": "", "name": "salt", "note": "to taste"}, {"quantity": "", "unit": "", "name": "black pepper", "note": "to taste"}]}]',
  '[{"step": 1, "title": "Prepare the onions", "content": "Peel the onions and cut them in half from top to bottom. Keeping them large helps them hold their shape while slowly softening in the broth.", "tip": "Use yellow onions for the best balance of sweetness and savoriness."}, {"step": 2, "title": "Build flavor", "content": "In a large pot, melt the butter with olive oil over medium heat. Add the onions cut-side down and let them lightly caramelize for a few minutes to boost natural sweetness.", "tip": "Do not rush this step—gentle browning adds depth to the onion boil."}, {"step": 3, "title": "Add the broth", "content": "Pour in the vegetable broth, making sure the onions are mostly submerged. Sprinkle in garlic powder, thyme, salt, and pepper.", "tip": "Vegetable broth keeps this recipe light, but chicken broth also works."}, {"step": 4, "title": "Simmer gently", "content": "Bring the pot to a gentle boil, then reduce to a simmer. Cook uncovered for about 35–40 minutes until the onions are very tender and the broth is deeply flavored.", "tip": "The longer it simmers, the closer it gets to a rich onion soup."}, {"step": 5, "title": "Serve warm", "content": "Taste and adjust seasoning if needed. Serve hot in bowls with plenty of broth and soft onions.", "tip": "Great with toasted bread or as a base for onion soup mix recipe ideas."}]',
  'Onion Boil Recipe | Cozy Winter Onion Soup',
  'Discover this cozy onion boil recipe, a simple winter meal made with tender onions and savory broth. Perfect for cold days and comfort cravings.',
  '[{"question_fr": "Peut-on préparer cette recette à l''avance?", "answer_fr": "Oui, l''onion boil se conserve très bien et est encore meilleur réchauffé.", "question_en": "Can this recipe be made ahead?", "answer_en": "Yes, onion boil stores well and tastes even better when reheated."}, {"question_fr": "Quelle est la différence avec une soupe à l''oignon?", "answer_fr": "L''onion boil est plus simple, sans farine ni fromage, mais tout aussi réconfortant.", "question_en": "What''s the difference between onion boil and onion soup?", "answer_en": "Onion boil is simpler, without flour or cheese, but just as comforting."}, {"question_fr": "Peut-on ajouter d''autres légumes?", "answer_fr": "Oui, carottes ou céleri se marient très bien avec cette soupe.", "question_en": "Can other vegetables be added?", "answer_en": "Yes, carrots or celery pair very well with this soup."}]',
  NOW()
FROM recipes
WHERE slug = 'bouillon-oignon-reconfortant';
