-- 1. Pain aux bananes ultra moelleux
INSERT INTO recipes (slug, title, excerpt, introduction, conclusion, prep_time, cook_time, total_time, servings, servings_unit, difficulty, ingredients, instructions, faq, featured_image, published_at)
VALUES (
  'pain-aux-bananes-moelleux',
  'Pain aux Bananes Ultra Moelleux',
  'La meilleure recette de pain aux bananes: ultra moelleux grâce au lait de coco et parfaitement sucré. Un classique réconfortant parfait pour le déjeuner.',
  '<p>Le <strong>pain aux bananes</strong> est un grand classique de la cuisine réconfortante. Cette version ultra moelleuse utilise du <strong>lait de coco</strong> qui apporte une texture incroyablement tendre et un léger goût exotique. C''est LA recette à faire quand vos bananes sont trop mûres!</p><p>Le secret de ce pain aux bananes parfait? Des bananes bien mûres (avec des taches brunes), un bon équilibre sucre-beurre, et surtout ne pas trop mélanger la pâte pour garder le moelleux.</p>',
  '<p>Ce pain aux bananes se conserve 3-4 jours à température ambiante bien emballé, ou jusqu''à 3 mois au congélateur. Réchauffez une tranche au grille-pain pour retrouver son moelleux!</p>',
  20, 60, 80, 10, 'tranches', 'facile',
  '[{"title": "Ingrédients", "items": [{"name": "farine tout usage", "quantity": "340", "unit": "g"}, {"name": "poudre à pâte", "quantity": "1", "unit": "c. à thé"}, {"name": "bicarbonate de soude", "quantity": "1", "unit": "c. à thé"}, {"name": "bananes mûres écrasées", "quantity": "310", "unit": "ml", "note": "3-4 bananes"}, {"name": "lait de coco", "quantity": "125", "unit": "ml"}, {"name": "jus de lime", "quantity": "1", "unit": "c. à soupe"}, {"name": "beurre non salé ramolli", "quantity": "115", "unit": "g"}, {"name": "sucre", "quantity": "210", "unit": "g"}, {"name": "oeuf", "quantity": "1", "unit": ""}, {"name": "extrait de vanille", "quantity": "1", "unit": "c. à thé"}]}]',
  '[{"step": 1, "title": "Préchauffer le four", "content": "Préchauffer le four à 180°C (350°F). Beurrer un moule à pain de 23 x 13 cm et tapisser le fond de papier parchemin."}, {"step": 2, "title": "Mélanger les ingrédients secs", "content": "Dans un bol, mélanger la farine, la poudre à pâte et le bicarbonate de soude. Réserver."}, {"step": 3, "title": "Préparer le mélange de bananes", "content": "Dans un autre bol, combiner les bananes écrasées, le lait de coco et le jus de lime."}, {"step": 4, "title": "Crémer le beurre", "content": "Au batteur électrique, crémer le beurre avec le sucre jusqu''à ce que le mélange soit léger et mousseux. Ajouter l''oeuf et la vanille, bien mélanger."}, {"step": 5, "title": "Incorporer les ingrédients", "content": "Incorporer les ingrédients secs en alternant avec le mélange de bananes, en commençant et terminant par les ingrédients secs. Ne pas trop mélanger."}, {"step": 6, "title": "Cuire", "content": "Verser dans le moule et cuire environ 1 heure, jusqu''à ce qu''un cure-dent inséré au centre en ressorte propre."}, {"step": 7, "title": "Refroidir", "content": "Laisser tiédir 10 minutes dans le moule, puis démouler sur une grille. Laisser refroidir complètement avant de trancher."}]',
  '[{"question": "Pourquoi mon pain aux bananes est-il sec?", "answer": "Un pain aux bananes sec résulte souvent d''une surcuisson ou de bananes pas assez mûres. Utilisez des bananes avec des taches brunes et surveillez la cuisson."}, {"question": "Peut-on remplacer le lait de coco?", "answer": "Oui, vous pouvez utiliser du lait entier, du babeurre ou du yogourt nature pour un résultat différent mais tout aussi moelleux."}, {"question": "Comment savoir si le pain est cuit?", "answer": "Insérez un cure-dent au centre. S''il en ressort propre ou avec quelques miettes sèches, c''est prêt."}, {"question": "Peut-on ajouter des noix ou du chocolat?", "answer": "Absolument! Ajoutez 125ml de noix de Grenoble ou de pépites de chocolat à la pâte."}, {"question": "Combien de temps se conserve le pain aux bananes?", "answer": "3-4 jours à température ambiante bien emballé, ou 3 mois au congélateur."}]',
  'https://images.unsplash.com/photo-1606101273945-e9eba7279e2c?w=1200',
  NOW()
) RETURNING id;

-- 2. Poulet au beurre indien (Butter Chicken)
INSERT INTO recipes (slug, title, excerpt, introduction, conclusion, prep_time, cook_time, total_time, servings, servings_unit, difficulty, ingredients, instructions, faq, featured_image, published_at)
VALUES (
  'poulet-au-beurre-indien',
  'Poulet au Beurre Indien (Butter Chicken)',
  'L''authentique poulet au beurre indien: poulet tendre dans une sauce tomate crémeuse épicée. Un classique de la cuisine indienne facile à faire maison.',
  '<p>Le <strong>poulet au beurre</strong> (Butter Chicken ou Murgh Makhani) est l''un des plats indiens les plus populaires au monde. Cette recette maison rivalise avec les meilleurs restaurants indiens: du poulet mariné au yogourt, rôti au four, puis mijoté dans une sauce tomate crémeuse parfumée au garam masala.</p><p>Le secret? La marinade au yogourt qui attendrit le poulet et le passage au four à haute température qui lui donne une légère croûte caramélisée.</p>',
  '<p>Servez ce poulet au beurre avec du riz basmati parfumé et du pain naan chaud pour une expérience indienne authentique. Les restes sont encore meilleurs le lendemain!</p>',
  25, 30, 55, 4, 'portions', 'moyen',
  '[{"title": "Marinade du poulet", "items": [{"name": "hauts de cuisses de poulet désossés", "quantity": "1", "unit": "kg"}, {"name": "yogourt nature", "quantity": "125", "unit": "ml"}, {"name": "gousses d''ail émincées", "quantity": "2", "unit": ""}, {"name": "gingembre frais émincé", "quantity": "1", "unit": "c. à soupe"}, {"name": "garam masala", "quantity": "1", "unit": "c. à soupe"}, {"name": "sel", "quantity": "1/2", "unit": "c. à thé"}, {"name": "jus de lime", "quantity": "1", "unit": "lime"}]}, {"title": "Sauce", "items": [{"name": "oignon haché", "quantity": "1", "unit": ""}, {"name": "jalapeño épépiné et haché", "quantity": "1", "unit": "petit"}, {"name": "gousses d''ail hachées", "quantity": "2", "unit": ""}, {"name": "gingembre frais haché", "quantity": "1", "unit": "c. à soupe"}, {"name": "beurre", "quantity": "40", "unit": "g"}, {"name": "garam masala", "quantity": "1", "unit": "c. à soupe"}, {"name": "pâte de tomates", "quantity": "1", "unit": "c. à soupe"}, {"name": "tomates en dés en conserve", "quantity": "398", "unit": "ml"}, {"name": "bouillon de poulet", "quantity": "125", "unit": "ml"}, {"name": "crème 35%", "quantity": "125", "unit": "ml"}, {"name": "coriandre fraîche hachée", "quantity": "1/4", "unit": "tasse"}]}]',
  '[{"step": 1, "title": "Mariner le poulet", "content": "Couper le poulet en cubes. Mélanger tous les ingrédients de la marinade dans un bol. Laisser mariner au moins 30 minutes (idéalement 2 heures)."}, {"step": 2, "title": "Cuire le poulet", "content": "Préchauffer le four à 260°C (500°F). Étendre le poulet sur une plaque tapissée de papier d''aluminium beurré. Cuire 15 minutes. Réserver."}, {"step": 3, "title": "Préparer la base de la sauce", "content": "Dans une grande casserole, faire revenir l''oignon, le jalapeño, l''ail et le gingembre dans le beurre à feu moyen jusqu''à ce qu''ils soient dorés."}, {"step": 4, "title": "Ajouter les épices", "content": "Ajouter le garam masala et la pâte de tomates. Cuire 2 minutes en remuant."}, {"step": 5, "title": "Mijoter la sauce", "content": "Ajouter les tomates et le bouillon. Assaisonner et laisser mijoter 15 minutes."}, {"step": 6, "title": "Crémer la sauce", "content": "Ajouter la crème. Mixer la sauce au pied-mélangeur jusqu''à consistance lisse."}, {"step": 7, "title": "Terminer le plat", "content": "Ajouter le poulet cuit à la sauce. Laisser mijoter quelques minutes. Garnir de coriandre et servir avec du riz et du naan."}]',
  '[{"question": "Qu''est-ce que le garam masala?", "answer": "C''est un mélange d''épices indiennes incluant cannelle, cardamome, clou de girofle, cumin et coriandre. On le trouve dans la section épices des supermarchés."}, {"question": "Peut-on utiliser des poitrines de poulet?", "answer": "Oui, mais les hauts de cuisses restent plus tendres et juteux. Si vous utilisez des poitrines, réduisez le temps de cuisson."}, {"question": "Comment rendre le plat moins épicé?", "answer": "Omettez le jalapeño ou réduisez la quantité de garam masala de moitié."}, {"question": "Peut-on préparer à l''avance?", "answer": "Oui! La sauce se conserve 3 jours au frigo. Réchauffez et ajoutez le poulet fraîchement cuit."}, {"question": "Quelle est l''origine du poulet au beurre?", "answer": "Le Butter Chicken a été inventé dans les années 1950 à Delhi, Inde, au restaurant Moti Mahal."}]',
  'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=1200',
  NOW()
) RETURNING id;

-- 3. Filets de porc glacés à l'érable
INSERT INTO recipes (slug, title, excerpt, introduction, conclusion, prep_time, cook_time, total_time, servings, servings_unit, difficulty, ingredients, instructions, faq, featured_image, published_at)
VALUES (
  'filets-de-porc-glaces-erable',
  'Filets de Porc Glacés à l''Érable',
  'Filets de porc tendres nappés d''une glace sucrée-salée au sirop d''érable et moutarde de Dijon. Un classique québécois prêt en 35 minutes.',
  '<p>Ces <strong>filets de porc glacés à l''érable</strong> incarnent parfaitement la cuisine québécoise: du bon porc local nappé de notre précieux sirop d''érable. La combinaison du sucré de l''érable avec le piquant de la moutarde de Dijon crée une sauce irrésistible.</p><p>Cette recette rapide (35 minutes!) est parfaite pour un souper de semaine élégant. Le porc reste rosé et juteux grâce à la cuisson au four après une saisie en poêle.</p>',
  '<p>Accompagnez ces filets de porc d''une purée de courge ou de pommes de terre à l''érable pour rester dans le thème. C''est un plat parfait pour les soirées d''automne!</p>',
  15, 20, 35, 6, 'portions', 'facile',
  '[{"title": "Ingrédients", "items": [{"name": "filets de porc", "quantity": "2", "unit": "", "note": "environ 450g chacun"}, {"name": "farine", "quantity": "1/4", "unit": "tasse"}, {"name": "beurre", "quantity": "1", "unit": "c. à soupe"}, {"name": "huile végétale", "quantity": "1", "unit": "c. à soupe"}, {"name": "échalotes françaises hachées", "quantity": "4", "unit": ""}, {"name": "sirop d''érable", "quantity": "125", "unit": "ml"}, {"name": "moutarde de Dijon", "quantity": "1", "unit": "c. à soupe"}, {"name": "sel et poivre", "quantity": "", "unit": "au goût"}]}]',
  '[{"step": 1, "title": "Préchauffer le four", "content": "Placer la grille au centre du four. Préchauffer à 180°C (350°F)."}, {"step": 2, "title": "Enfariner les filets", "content": "Mettre la farine dans une assiette. Enrober les filets de porc de farine en secouant l''excédent."}, {"step": 3, "title": "Saisir le porc", "content": "Dans une poêle allant au four à feu moyen-élevé, faire dorer les filets dans le beurre et l''huile, environ 2 minutes de chaque côté. Saler et poivrer. Réserver sur une assiette."}, {"step": 4, "title": "Préparer la glace", "content": "Dans la même poêle, faire revenir les échalotes 1 minute. Ajouter le sirop d''érable et la moutarde. Laisser mijoter 1 minute jusqu''à léger épaississement."}, {"step": 5, "title": "Glacer et cuire", "content": "Remettre les filets dans la poêle et les enrober de sauce. Cuire au four 16-17 minutes pour une cuisson rosée."}, {"step": 6, "title": "Repos et service", "content": "Retirer du four, couvrir de papier d''aluminium et laisser reposer 5 minutes. Trancher et servir nappé de sauce."}]',
  '[{"question": "Comment savoir si le porc est cuit?", "answer": "La température interne doit atteindre 63°C (145°F) pour une cuisson rosée et juteuse. Le porc peut rester légèrement rosé au centre."}, {"question": "Peut-on utiliser un autre morceau de porc?", "answer": "Les côtelettes de porc fonctionnent aussi, mais ajustez le temps de cuisson selon l''épaisseur."}, {"question": "Comment éviter que le porc soit sec?", "answer": "Ne pas surcuire! Le temps de repos est crucial pour redistribuer les jus."}, {"question": "Peut-on préparer la sauce à l''avance?", "answer": "Oui, préparez la glace à l''érable et réchauffez-la au moment de servir."}, {"question": "Quel sirop d''érable utiliser?", "answer": "Utilisez du sirop d''érable pur de catégorie A ambré ou foncé pour plus de saveur."}]',
  'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=1200',
  NOW()
) RETURNING id;

-- 4. Soupe à l'oignon gratinée
INSERT INTO recipes (slug, title, excerpt, introduction, conclusion, prep_time, cook_time, total_time, servings, servings_unit, difficulty, ingredients, instructions, faq, featured_image, published_at)
VALUES (
  'soupe-a-loignon-gratinee',
  'Soupe à l''Oignon Gratinée',
  'La meilleure soupe à l''oignon: oignons caramélisés, bouillon riche, croûtons et fromage gratiné. Un classique français réconfortant.',
  '<p>La <strong>soupe à l''oignon gratinée</strong> est l''un des plats les plus réconfortants de la cuisine française. Le secret réside dans la caramélisation lente des oignons qui développe des saveurs profondes et sucrées, puis le gratin doré de gruyère qui croustille sous le gril.</p><p>Cette recette prend du temps mais la plupart est passive. Les oignons mijotent doucement pendant que vous vaquez à vos occupations. Le résultat: une soupe digne des meilleurs bistrots parisiens!</p>',
  '<p>Servez cette soupe comme entrée généreuse ou comme plat principal léger avec une salade verte. Attention aux bols brûlants sortis du four!</p>',
  20, 65, 85, 4, 'portions', 'moyen',
  '[{"title": "Soupe", "items": [{"name": "oignons jaunes", "quantity": "6", "unit": "gros"}, {"name": "beurre", "quantity": "55", "unit": "g"}, {"name": "vin rouge", "quantity": "125", "unit": "ml"}, {"name": "cognac ou brandy", "quantity": "30", "unit": "ml"}, {"name": "bouillon de poulet", "quantity": "1", "unit": "litre"}, {"name": "bouillon de boeuf", "quantity": "1", "unit": "litre"}, {"name": "farine grillée", "quantity": "1", "unit": "c. à soupe"}, {"name": "muscade moulue", "quantity": "1", "unit": "pincée"}]}, {"title": "Garniture", "items": [{"name": "tranches de baguette", "quantity": "12", "unit": "", "note": "1 cm d''épaisseur, grillées"}, {"name": "gousse d''ail coupée en deux", "quantity": "1", "unit": ""}, {"name": "gruyère râpé", "quantity": "200", "unit": "g"}]}]',
  '[{"step": 1, "title": "Préparer les oignons", "content": "Couper les oignons en quartiers, puis émincer chaque quartier en lanières courtes."}, {"step": 2, "title": "Caraméliser les oignons", "content": "Dans une grande casserole à feu moyen, faire fondre les oignons dans le beurre 15 minutes en remuant occasionnellement. Augmenter le feu et cuire 15 minutes supplémentaires jusqu''à caramélisation, en remuant constamment et en grattant le fond."}, {"step": 3, "title": "Déglacer", "content": "Déglacer avec le vin et le cognac. Laisser réduire presque à sec."}, {"step": 4, "title": "Ajouter les bouillons", "content": "Ajouter les bouillons, la farine et la muscade. Bien mélanger."}, {"step": 5, "title": "Mijoter", "content": "Porter à ébullition puis laisser mijoter 30 minutes jusqu''à réduction de moitié (environ 1,25 litre). Saler et poivrer."}, {"step": 6, "title": "Préparer les croûtons", "content": "Préchauffer le gril du four. Frotter les croûtons avec l''ail. Déposer les bols sur une plaque à biscuits."}, {"step": 7, "title": "Gratiner", "content": "Répartir la soupe dans les bols. Ajouter 30ml de fromage, 3 croûtons, puis le reste du fromage. Gratiner 5 minutes jusqu''à ce que le fromage soit doré et bouillonnant."}]',
  '[{"question": "Pourquoi caraméliser les oignons si longtemps?", "answer": "La caramélisation lente développe les sucres naturels des oignons et crée une saveur profonde et complexe impossible à obtenir autrement."}, {"question": "Quel vin utiliser?", "answer": "Un vin rouge sec comme un Côtes du Rhône ou un Pinot Noir. Évitez les vins trop tanniques ou sucrés."}, {"question": "Peut-on préparer la soupe à l''avance?", "answer": "Oui! La soupe (sans croûtons ni fromage) se conserve 3 jours au frigo. Réchauffez et gratinez au moment de servir."}, {"question": "Quel fromage utiliser?", "answer": "Le gruyère est traditionnel, mais l''emmental ou le comté fonctionnent aussi très bien."}, {"question": "Comment éviter que le fromage brûle?", "answer": "Surveillez de près sous le gril et gardez les bols au centre du four, pas trop près de l''élément."}]',
  'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200',
  NOW()
) RETURNING id;

-- 5. Gâteau aux carottes
INSERT INTO recipes (slug, title, excerpt, introduction, conclusion, prep_time, cook_time, total_time, servings, servings_unit, difficulty, ingredients, instructions, faq, featured_image, published_at)
VALUES (
  'gateau-aux-carottes-meilleur',
  'Gâteau aux Carottes (Le Meilleur)',
  'Le meilleur gâteau aux carottes: moelleux, épicé, garni de noix et nappé d''un glaçage au fromage à la crème onctueux.',
  '<p>Ce <strong>gâteau aux carottes</strong> est tout simplement le meilleur que vous goûterez! Ultra moelleux grâce aux carottes râpées et au jus d''orange, parfumé à la cannelle et à la muscade, garni de noix croquantes et de raisins secs.</p><p>Le secret? Monter les blancs d''oeufs en neige et les incorporer délicatement pour une texture aérienne. Le glaçage au fromage à la crème apporte la touche finale parfaite avec son équilibre sucré-acidulé.</p>',
  '<p>Ce gâteau se conserve 5 jours au réfrigérateur. Sortez-le 30 minutes avant de servir pour que le glaçage soit plus crémeux.</p>',
  40, 70, 110, 12, 'portions', 'moyen',
  '[{"title": "Gâteau", "items": [{"name": "farine tout usage", "quantity": "560", "unit": "ml"}, {"name": "poudre à pâte", "quantity": "1 1/2", "unit": "c. à thé"}, {"name": "bicarbonate de soude", "quantity": "1/2", "unit": "c. à thé"}, {"name": "cannelle moulue", "quantity": "1/2", "unit": "c. à thé"}, {"name": "muscade moulue", "quantity": "1/2", "unit": "c. à thé"}, {"name": "sel", "quantity": "1/4", "unit": "c. à thé"}, {"name": "oeufs séparés", "quantity": "4", "unit": ""}, {"name": "cassonade", "quantity": "430", "unit": "ml"}, {"name": "huile de canola", "quantity": "180", "unit": "ml"}, {"name": "jus d''orange", "quantity": "125", "unit": "ml"}, {"name": "carottes pelées et râpées", "quantity": "1", "unit": "litre"}, {"name": "noix de Grenoble hachées", "quantity": "250", "unit": "ml"}, {"name": "raisins secs", "quantity": "125", "unit": "ml"}]}, {"title": "Glaçage", "items": [{"name": "fromage à la crème ramolli", "quantity": "250", "unit": "g"}, {"name": "beurre non salé ramolli", "quantity": "30", "unit": "ml"}, {"name": "sucre à glacer", "quantity": "750", "unit": "ml"}]}]',
  '[{"step": 1, "title": "Préparer les moules", "content": "Préchauffer le four à 180°C (350°F). Beurrer deux moules à charnière de 20 cm et tapisser le fond de papier parchemin."}, {"step": 2, "title": "Mélanger les ingrédients secs", "content": "Dans un bol, mélanger la farine, la poudre à pâte, le bicarbonate, les épices et le sel."}, {"step": 3, "title": "Monter les blancs", "content": "Fouetter les blancs d''oeufs jusqu''à formation de mousse. Ajouter graduellement 250 ml de cassonade en fouettant jusqu''à obtention de pics fermes."}, {"step": 4, "title": "Préparer la base", "content": "Dans un autre bol, mélanger les jaunes d''oeufs, l''huile, le jus d''orange et le reste de la cassonade."}, {"step": 5, "title": "Assembler la pâte", "content": "Incorporer les ingrédients secs au mélange de jaunes. Incorporer délicatement les blancs montés, puis les carottes, noix et raisins."}, {"step": 6, "title": "Cuire", "content": "Répartir entre les moules. Cuire 1h10 ou jusqu''à ce qu''un cure-dent en ressorte propre. Laisser refroidir complètement."}, {"step": 7, "title": "Préparer le glaçage", "content": "Battre le fromage à la crème et le beurre. Ajouter graduellement le sucre à glacer jusqu''à consistance lisse et crémeuse."}, {"step": 8, "title": "Glacer le gâteau", "content": "Démouler les gâteaux. Étendre le glaçage entre les étages et sur le dessus du gâteau."}]',
  '[{"question": "Pourquoi mon gâteau est-il dense?", "answer": "Assurez-vous de bien monter les blancs en neige et de les incorporer délicatement. Ne pas trop mélanger!"}, {"question": "Peut-on congeler ce gâteau?", "answer": "Oui, sans le glaçage, il se congèle 3 mois. Glacez après décongélation."}, {"question": "Comment râper les carottes?", "answer": "Utilisez le côté à gros trous d''une râpe à boîte ou le disque à râper d''un robot culinaire."}, {"question": "Peut-on omettre les noix?", "answer": "Oui, remplacez-les par des flocons de noix de coco non sucrés pour texture similaire."}, {"question": "Le glaçage est-il obligatoire?", "answer": "Non, mais c''est la combinaison parfaite! Vous pouvez aussi saupoudrer de sucre à glacer."}]',
  'https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=1200',
  NOW()
) RETURNING id;

-- 6. Tartare de boeuf
INSERT INTO recipes (slug, title, excerpt, introduction, conclusion, prep_time, cook_time, total_time, servings, servings_unit, difficulty, ingredients, instructions, faq, featured_image, published_at)
VALUES (
  'tartare-de-boeuf-classique',
  'Tartare de Boeuf Classique',
  'Le meilleur tartare de boeuf: filet de boeuf ultra-frais, assaisonnement parfait au sambal oelek et moutarde. Un classique des bistros.',
  '<p>Le <strong>tartare de boeuf</strong> est un plat emblématique qui met en valeur la qualité de la viande crue. Cette version classique combine du filet de boeuf ultra-frais avec une vinaigrette relevée au sambal oelek, deux moutardes et des câpres pour un équilibre parfait.</p><p>Le secret d''un bon tartare? Une viande de première qualité, des couteaux bien aiguisés, et garder tout très froid pendant la préparation.</p>',
  '<p>Servez le tartare immédiatement avec des croûtons de baguette grillés, des frites maison et une salade verte. Ne préparez jamais le tartare à l''avance!</p>',
  30, 0, 30, 4, 'portions', 'moyen',
  '[{"title": "Ingrédients", "items": [{"name": "jus de citron", "quantity": "30", "unit": "ml"}, {"name": "moutarde de Dijon", "quantity": "30", "unit": "ml"}, {"name": "moutarde à l''ancienne", "quantity": "15", "unit": "ml"}, {"name": "jaune d''oeuf", "quantity": "1", "unit": ""}, {"name": "câpres égouttées et hachées", "quantity": "15", "unit": "ml"}, {"name": "sambal oelek", "quantity": "10", "unit": "ml"}, {"name": "huile d''olive", "quantity": "60", "unit": "ml"}, {"name": "filet de boeuf très frais", "quantity": "675", "unit": "g"}, {"name": "persil plat haché", "quantity": "30", "unit": "ml"}, {"name": "ciboulette hachée", "quantity": "45", "unit": "ml"}, {"name": "échalotes françaises émincées", "quantity": "45", "unit": "ml"}]}]',
  '[{"step": 1, "title": "Préparer la vinaigrette", "content": "Dans un grand bol, mélanger le jus de citron, les deux moutardes, le jaune d''oeuf, les câpres et le sambal oelek."}, {"step": 2, "title": "Émulsionner", "content": "Ajouter l''huile d''olive en filet en fouettant continuellement jusqu''à émulsion."}, {"step": 3, "title": "Hacher la viande", "content": "À l''aide d''un couteau bien aiguisé, hacher finement le filet de boeuf au couteau (ne pas utiliser de robot culinaire)."}, {"step": 4, "title": "Assembler", "content": "Ajouter la viande, les herbes et les échalotes à la vinaigrette. Saler, poivrer et bien mélanger."}, {"step": 5, "title": "Servir immédiatement", "content": "Servir aussitôt avec des croûtons de baguette grillés, des frites maison et une salade verte."}]',
  '[{"question": "Quelle coupe de boeuf utiliser?", "answer": "Le filet de boeuf (filet mignon) est idéal car il est très tendre et maigre. L''intérieur de ronde fonctionne aussi."}, {"question": "Comment garder la viande froide?", "answer": "Placez un bol sur de la glace pendant la préparation. Travaillez rapidement."}, {"question": "Le tartare est-il sécuritaire?", "answer": "Avec de la viande très fraîche de qualité et une préparation hygiénique, oui. Évitez si immunodéprimé, enceinte ou très jeune/âgé."}, {"question": "Qu''est-ce que le sambal oelek?", "answer": "Une pâte de piments indonésienne. Remplacez par de la sriracha ou du piment fort haché."}, {"question": "Peut-on préparer à l''avance?", "answer": "Non! Le tartare doit être préparé et servi immédiatement pour des raisons de fraîcheur et de sécurité."}]',
  'https://images.unsplash.com/photo-1626645738196-c2a72c97cf47?w=1200',
  NOW()
) RETURNING id;

-- 7. Soupe aux pois traditionnelle
INSERT INTO recipes (slug, title, excerpt, introduction, conclusion, prep_time, cook_time, total_time, servings, servings_unit, difficulty, ingredients, instructions, faq, featured_image, published_at)
VALUES (
  'soupe-aux-pois-traditionnelle',
  'Soupe aux Pois Traditionnelle',
  'L''authentique soupe aux pois québécoise: pois jaunes, lard salé et sarriette. Un classique réconfortant de notre patrimoine culinaire.',
  '<p>La <strong>soupe aux pois</strong> est un pilier de la cuisine traditionnelle québécoise. Héritée des premiers colons français, cette soupe nourrissante a réchauffé des générations de Québécois pendant les longs hivers.</p><p>Cette recette authentique utilise du lard salé (ou flanc de porc) et de la sarriette, l''herbe emblématique de notre cuisine. Le secret? Un long mijotage qui fait fondre les pois en une purée crémeuse.</p>',
  '<p>Servez cette soupe fumante avec du pain de ménage grillé et beurré. Les restes sont encore meilleurs réchauffés le lendemain!</p>',
  15, 180, 195, 8, 'portions', 'facile',
  '[{"title": "Ingrédients", "items": [{"name": "pois jaunes entiers", "quantity": "310", "unit": "g", "note": "rincés"}, {"name": "flanc de porc salé", "quantity": "115", "unit": "g", "note": "coupé en deux"}, {"name": "oignons hachés", "quantity": "375", "unit": "g"}, {"name": "beurre", "quantity": "30", "unit": "ml"}, {"name": "carottes en dés", "quantity": "145", "unit": "g"}, {"name": "céleri en dés", "quantity": "135", "unit": "g"}, {"name": "eau", "quantity": "1.5", "unit": "litre"}, {"name": "feuilles de laurier", "quantity": "3", "unit": ""}, {"name": "sarriette ciselée", "quantity": "2", "unit": "c. à thé", "note": "ou 1/2 c. à thé moulue"}]}]',
  '[{"step": 1, "title": "Tremper les pois", "content": "Faire tremper les pois 4 heures ou toute une nuit, couverts d''eau. Égoutter et jeter l''eau de trempage."}, {"step": 2, "title": "Dessaler le porc", "content": "Faire tremper le flanc de porc 15 minutes dans l''eau froide pour le dessaler légèrement. Égoutter."}, {"step": 3, "title": "Faire revenir les légumes", "content": "Dans une grande casserole, faire dorer les oignons dans le beurre. Ajouter les carottes et le céleri, cuire 5 minutes."}, {"step": 4, "title": "Mijoter", "content": "Ajouter l''eau, les pois, le porc et les feuilles de laurier. Porter à ébullition puis réduire le feu. Couvrir et laisser mijoter 2h30 à 3 heures."}, {"step": 5, "title": "Préparer le porc", "content": "Retirer le porc de la casserole. Enlever le gras, hacher la viande en petits dés et remettre dans la soupe."}, {"step": 6, "title": "Assaisonner", "content": "Ajouter la sarriette. Rectifier l''assaisonnement en sel et poivre. Servir bien chaud."}]',
  '[{"question": "Pourquoi faire tremper les pois?", "answer": "Le trempage ramollit les pois et réduit le temps de cuisson. Il aide aussi à les rendre plus digestibles."}, {"question": "Peut-on utiliser des pois cassés?", "answer": "Oui, mais ils cuiront plus vite (environ 1h30). La texture sera plus lisse."}, {"question": "Qu''est-ce que la sarriette?", "answer": "Une herbe aromatique typique du Québec, aussi appelée herbe à fèves. Elle parfume traditionnellement les légumineuses."}, {"question": "Comment épaissir la soupe?", "answer": "En fin de cuisson, écrasez une partie des pois avec le dos d''une cuillère ou utilisez un pied-mélangeur partiellement."}, {"question": "Peut-on congeler cette soupe?", "answer": "Oui! Elle se congèle très bien jusqu''à 3 mois. Décongelez au frigo et réchauffez doucement."}]',
  'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=1200',
  NOW()
) RETURNING id;
