-- ============================================================
-- Import batch 4 d'épices pour La Route des Épices
-- 86 épices de base avec noms FR/EN
-- ============================================================

INSERT INTO spices (slug, name_fr, name_en, is_published, categories, taste_profile) VALUES
('ail-roti-seche', 'Ail rôti séché', 'Roasted garlic', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ail-sauvage', 'Ail sauvage', 'Wild garlic', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('anis-des-montagnes', 'Anis des montagnes', 'Mountain anise', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('argousier-baies-sechees', 'Argousier (baies séchées)', 'Sea buckthorn berry', true, ARRAY['doux', 'nordique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('asperule-odorante', 'Aspérule odorante', 'Sweet woodruff', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-eglantier', 'Baie d''églantier', 'Rose hip', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-sureau-sechee', 'Baie de sureau séchée', 'Dried elderberry', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-sichuan-verte', 'Baie du Sichuan verte', 'Green Sichuan pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('basilic-africain', 'Basilic africain', 'African basil', true, ARRAY['doux', 'africain'], '{"intensity": 3, "spicy": 0}'::jsonb),
('basilic-pourpre', 'Basilic pourpre', 'Purple basil', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('bois-reglisse', 'Bois de réglisse', 'Licorice wood', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('bouton-jasmin', 'Bouton de jasmin', 'Jasmine bud', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('cannelle-saigon', 'Cannelle de Saigon', 'Saigon cinnamon', true, ARRAY['doux', 'asiatique'], '{"intensity": 5, "spicy": 0}'::jsonb),
('cannelle-fumee', 'Cannelle fumée', 'Smoked cinnamon', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cardamome-ethiopie', 'Cardamome d''Éthiopie', 'Ethiopian cardamom', true, ARRAY['doux', 'africain'], '{"intensity": 4, "spicy": 0}'::jsonb),
('carvi-brun', 'Carvi brun', 'Brown caraway', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cassis-seche', 'Cassis séché', 'Dried blackcurrant', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('cerfeuil-sauvage', 'Cerfeuil sauvage', 'Wild chervil', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 2, "spicy": 0}'::jsonb),
('chili-chiltepin', 'Chili chiltepin', 'Chiltepin chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 5}'::jsonb),
('chili-ghost', 'Chili ghost (bhut jolokia)', 'Ghost pepper', true, ARRAY['piquant', 'indien'], '{"intensity": 5, "spicy": 5}'::jsonb),
('chili-scorpion', 'Chili scorpion', 'Scorpion pepper', true, ARRAY['piquant', 'caraibes'], '{"intensity": 5, "spicy": 5}'::jsonb),
('ciboulette-chinoise', 'Ciboulette chinoise', 'Chinese chives', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('citron-caviar-seche', 'Citron caviar séché', 'Dried finger lime', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('clou-girofle-rose', 'Clou de girofle rose', 'Pink clove', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('coriandre-longue', 'Coriandre longue', 'Long coriander', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cumin-royal', 'Cumin royal', 'Royal cumin', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('curcuma-fume', 'Curcuma fumé', 'Smoked turmeric', true, ARRAY['doux', 'fume', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ecorce-bouleau', 'Écorce de bouleau', 'Birch bark spice', true, ARRAY['doux', 'nordique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('ecorce-cannelle-verte', 'Écorce de cannelle verte', 'Green cinnamon bark', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ecorce-mangoustan', 'Écorce de mangoustan', 'Mangosteen rind', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('estragon-mexicain', 'Estragon mexicain', 'Mexican tarragon', true, ARRAY['doux', 'mexicain'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenouil-indien', 'Fenouil indien', 'Indian fennel', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenugrec-germe-seche', 'Fenugrec germé séché', 'Sprouted fenugreek', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('feve-tonka-rapee', 'Fève tonka râpée', 'Grated tonka bean', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('fleur-oranger-sechee', 'Fleur d''oranger séchée', 'Dried orange blossom', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 2, "spicy": 0}'::jsonb),
('fleur-coriandre', 'Fleur de coriandre', 'Coriander flower', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('fleur-thym', 'Fleur de thym', 'Thyme flower', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('galanga-fume', 'Galanga fumé', 'Smoked galangal', true, ARRAY['doux', 'fume', 'asiatique'], '{"intensity": 4, "spicy": 1}'::jsonb),
('genievre-rouge', 'Genièvre rouge', 'Red juniper berry', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('gingembre-noir', 'Gingembre noir', 'Black ginger', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('graines-aneth-moulues', 'Graines d''aneth moulues', 'Ground dill seed', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-basilic', 'Graines de basilic', 'Basil seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-chanvre', 'Graines de chanvre', 'Hemp seed', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('graines-chia', 'Graines de chia', 'Chia seed', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('graines-moutarde-sauvage', 'Graines de moutarde sauvage', 'Wild mustard seed', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('graines-nigelle-sauvage', 'Graines de nigelle sauvage', 'Wild nigella seed', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-poivre-rose-moulues', 'Graines de poivre rose moulues', 'Ground pink peppercorn', true, ARRAY['doux'], '{"intensity": 2, "spicy": 1}'::jsonb),
('graines-sesame-grillees', 'Graines de sésame grillées', 'Toasted sesame seed', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('herbe-tigre', 'Herbe du tigre', 'Tiger grass', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('hysope-anisee', 'Hysope anisée', 'Anise hyssop', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('kaffir-lime-entier-seche', 'Kaffir lime entier séché', 'Whole dried kaffir lime', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('laurier-indien', 'Laurier indien', 'Indian bay leaf', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('liveche-sauvage', 'Livèche sauvage', 'Wild lovage', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('macis-sauvage', 'Macis sauvage', 'Wild mace', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('melange-barbecue-epice', 'Mélange barbecue épicé', 'Spicy barbecue rub', true, ARRAY['piquant', 'melange', 'americain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('melange-cajun', 'Mélange cajun', 'Cajun spice mix', true, ARRAY['piquant', 'melange', 'americain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('melange-creole', 'Mélange créole', 'Creole spice blend', true, ARRAY['piquant', 'melange', 'caraibes'], '{"intensity": 3, "spicy": 2}'::jsonb),
('dukkah', 'Mélange dukkah', 'Dukkah', true, ARRAY['doux', 'melange', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('melange-jerk', 'Mélange jerk', 'Jerk seasoning', true, ARRAY['piquant', 'melange', 'caraibes'], '{"intensity": 4, "spicy": 4}'::jsonb),
('menthe-chocolat', 'Menthe chocolat', 'Chocolate mint', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('muscade-fumee', 'Muscade fumée', 'Smoked nutmeg', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb),
('oignon-roti-seche', 'Oignon rôti séché', 'Roasted dried onion', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('origan-grec', 'Origan grec', 'Greek oregano', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('paprika-noir', 'Paprika noir', 'Black paprika', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 1}'::jsonb),
('piment-carolina-reaper', 'Piment carolina reaper', 'Carolina Reaper', true, ARRAY['piquant', 'americain'], '{"intensity": 5, "spicy": 5}'::jsonb),
('piment-jamaicain-fume', 'Piment jamaïcain fumé', 'Smoked allspice', true, ARRAY['doux', 'fume', 'caraibes'], '{"intensity": 4, "spicy": 0}'::jsonb),
('poivre-andaliman', 'Poivre andaliman', 'Andaliman pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-cubebe-fume', 'Poivre de Cubèbe fumé', 'Smoked cubeb pepper', true, ARRAY['piquant', 'fume'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-java', 'Poivre de Java', 'Java pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('poivre-tasmanie', 'Poivre de Tasmanie', 'Tasmanian pepperberry', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 3}'::jsonb),
('poivre-sauvage-africain', 'Poivre sauvage africain', 'African wild pepper', true, ARRAY['piquant', 'africain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('racine-curcuma-sechee', 'Racine de curcuma séchée', 'Dried turmeric root', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('racine-gingembre-fumee', 'Racine de gingembre fumée', 'Smoked ginger root', true, ARRAY['piquant', 'fume'], '{"intensity": 4, "spicy": 2}'::jsonb),
('reglisse-etoilee', 'Réglisse étoilée', 'Star licorice', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('romarin-sauvage', 'Romarin sauvage', 'Wild rosemary', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('safran-espagnol', 'Safran espagnol', 'Spanish saffron', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 5, "spicy": 0}'::jsonb),
('safran-iranien', 'Safran iranien', 'Iranian saffron', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 5, "spicy": 0}'::jsonb),
('sarriette-ete', 'Sarriette d''été', 'Summer savory', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('sarriette-hiver', 'Sarriette d''hiver', 'Winter savory', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('shiso-pourpre', 'Shiso pourpre', 'Purple shiso', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('sumac-fume', 'Sumac fumé', 'Smoked sumac', true, ARRAY['doux', 'fume', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('tamarin-concentre', 'Tamarin concentré', 'Tamarind concentrate', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('thym-fume', 'Thym fumé', 'Smoked thyme', true, ARRAY['doux', 'fume', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('vanille-bourbon', 'Vanille bourbon', 'Bourbon vanilla', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('vanille-mexicaine', 'Vanille mexicaine', 'Mexican vanilla', true, ARRAY['doux', 'mexicain'], '{"intensity": 4, "spicy": 0}'::jsonb),
('zeste-yuzu-seche', 'Zeste de yuzu séché', 'Dried yuzu zest', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  categories = EXCLUDED.categories,
  taste_profile = EXCLUDED.taste_profile,
  is_published = EXCLUDED.is_published;

-- Afficher le nombre d'épices
SELECT COUNT(*) as total_spices FROM spices WHERE is_published = true;
