-- ============================================================
-- Import batch 3 d'épices pour La Route des Épices
-- 91 épices avec noms FR/EN
-- ============================================================

INSERT INTO spices (slug, name_fr, name_en, is_published, categories, taste_profile) VALUES
('achiote-roucou', 'Achiote (roucou)', 'Annatto seed', true, ARRAY['doux', 'mexicain', 'caraibes'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ail-des-ours-seche', 'Ail des ours séché', 'Wild garlic', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('anis-bleu', 'Anis bleu', 'Blue anise', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('arbre-curry-graines', 'Arbre à curry (graines)', 'Curry tree seed', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('asaret', 'Asaret', 'Wild ginger', true, ARRAY['doux'], '{"intensity": 3, "spicy": 1}'::jsonb),
('badiane-moulue', 'Badiane moulue', 'Ground star anise', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('baie-myrte', 'Baie de myrte', 'Myrtle berry', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('baie-poivre-cubebe', 'Baie de poivre cubèbe', 'Cubeb berry', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 2}'::jsonb),
('baie-sansho', 'Baie de sansho', 'Sansho pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('basilic-sacre-tulsi', 'Basilic sacré (Tulsi)', 'Holy basil', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('berbere', 'Berbéré (mélange)', 'Berbere spice mix', true, ARRAY['piquant', 'melange', 'africain'], '{"intensity": 4, "spicy": 4}'::jsonb),
('betel-feuille-sechee', 'Bétel (feuille séchée)', 'Betel leaf', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('bhringraj', 'Bhringraj', 'False daisy', true, ARRAY['doux', 'indien'], '{"intensity": 2, "spicy": 0}'::jsonb),
('bois-inde', 'Bois d''Inde', 'Allspice', true, ARRAY['doux', 'caraibes'], '{"intensity": 4, "spicy": 0}'::jsonb),
('bouton-rose-seche', 'Bouton de rose séché', 'Dried rosebud', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 2, "spicy": 0}'::jsonb),
('bouton-cassis', 'Bouton de cassis', 'Blackcurrant bud', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('caloupile-seche', 'Caloupilé séché', 'Dried curry leaf', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('camomille', 'Camomille', 'Chamomile', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('cardamome-blanche', 'Cardamome blanche', 'White cardamom', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cardamome-chinoise', 'Cardamome chinoise', 'Chinese cardamom', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('caroube', 'Caroube', 'Carob powder', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cassia-poudre', 'Cassia en poudre', 'Ground cassia', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cedrat-seche', 'Cédrat séché', 'Dried citron peel', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('chili-arbol', 'Chili árbol', 'Arbol chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 4}'::jsonb),
('chili-pasilla', 'Chili pasilla', 'Pasilla chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('citronnelle', 'Citronnelle', 'Lemongrass', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('citron-noir-loomi', 'Citron noir (loomi)', 'Dried black lime', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 4, "spicy": 0}'::jsonb),
('clou-girofle-moulu', 'Clou de girofle moulu', 'Ground clove', true, ARRAY['doux'], '{"intensity": 5, "spicy": 0}'::jsonb),
('coriandre-racine', 'Coriandre racine', 'Coriander root', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cresson-alenois-graines', 'Cresson alénois (graines)', 'Garden cress seed', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('cumin-des-pres', 'Cumin des prés', 'Meadow cumin', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cumin-vert', 'Cumin vert', 'Green cumin', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('curcuma-blanc', 'Curcuma blanc', 'White turmeric', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('curcuma-noir', 'Curcuma noir', 'Black turmeric', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('dill-pollen', 'Dill pollen', 'Dill pollen', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ecorce-orange-amere', 'Écorce d''orange amère', 'Bitter orange peel', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ecorce-citron', 'Écorce de citron', 'Lemon peel', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('epazote', 'Épazote', 'Epazote', true, ARRAY['doux', 'mexicain'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenugrec-moulu', 'Fenugrec moulu', 'Ground fenugreek', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('feve-calabar', 'Fève de calabar', 'Calabar bean', true, ARRAY['doux', 'africain'], '{"intensity": 2, "spicy": 0}'::jsonb),
('feuille-combava-sechee', 'Feuille de combava séchée', 'Dried kaffir lime leaf', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('fleur-bananier-sechee', 'Fleur de bananier séchée', 'Dried banana blossom', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('fleur-cannelle', 'Fleur de cannelle', 'Cinnamon flower', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fleur-sel-epicee', 'Fleur de sel épicée', 'Spiced sea salt', true, ARRAY['doux', 'melange'], '{"intensity": 2, "spicy": 0}'::jsonb),
('fleur-sureau', 'Fleur de sureau', 'Elderflower', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('galanga-rouge', 'Galanga rouge', 'Red galangal', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('genievre-moulu', 'Genièvre moulu', 'Ground juniper', true, ARRAY['doux', 'nordique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('gingembre-sauvage', 'Gingembre sauvage', 'Wild ginger', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 2}'::jsonb),
('graines-angelique', 'Graines d''angélique', 'Angelica seed', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-carotte', 'Graines de carotte', 'Carrot seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-cumin-noir', 'Graines de cumin noir', 'Black cumin seed', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('graines-fenouil-sauvage', 'Graines de fenouil sauvage', 'Wild fennel seed', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-lin', 'Graines de lin', 'Flaxseed', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('graines-moutarde-brune', 'Graines de moutarde brune', 'Brown mustard seed', true, ARRAY['piquant', 'indien'], '{"intensity": 3, "spicy": 2}'::jsonb),
('graines-roquette', 'Graines de roquette', 'Arugula seed', true, ARRAY['piquant'], '{"intensity": 2, "spicy": 1}'::jsonb),
('graines-sene', 'Graines de séné', 'Senna seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-tournesol-grillees', 'Graines de tournesol grillées', 'Roasted sunflower seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('herbe-curry', 'Herbe à curry', 'Curry herb', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('hysope', 'Hysope', 'Hyssop', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('kaloupile-moulu', 'Kaloupilé moulu', 'Ground curry leaf', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('kencur', 'Kencur', 'Aromatic ginger', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 1}'::jsonb),
('lime-sechee', 'Lime séchée', 'Dried lime', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('liveche', 'Livèche', 'Lovage', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('macis-moulu', 'Macis moulu', 'Ground mace', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('mandarine-sechee', 'Mandarine séchée', 'Dried mandarin peel', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('melilot', 'Mélilot', 'Sweet clover', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('menthe-poivree-sechee', 'Menthe poivrée séchée', 'Dried peppermint', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('moutarde-verte', 'Moutarde verte', 'Green mustard', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('nigelle-moulue', 'Nigelle moulue', 'Ground nigella', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('noix-kola', 'Noix de kola', 'Kola nut', true, ARRAY['doux', 'africain'], '{"intensity": 3, "spicy": 0}'::jsonb),
('noix-muscade-longue', 'Noix muscade longue', 'Long nutmeg', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('origan-mexicain', 'Origan mexicain', 'Mexican oregano', true, ARRAY['doux', 'mexicain'], '{"intensity": 4, "spicy": 0}'::jsonb),
('paprika-espagnol', 'Paprika espagnol', 'Spanish paprika', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 1}'::jsonb),
('paprika-hongrois', 'Paprika hongrois', 'Hungarian paprika', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 1}'::jsonb),
('piment-cascabel', 'Piment cascabel', 'Cascabel chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-mulato', 'Piment mulato', 'Mulato chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-piquin', 'Piment piquín', 'Pequin chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 5}'::jsonb),
('poivre-kampot', 'Poivre de Kampot', 'Kampot pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('poivre-sarawak', 'Poivre de Sarawak', 'Sarawak pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-tellicherry', 'Poivre de Tellicherry', 'Tellicherry pepper', true, ARRAY['piquant', 'indien'], '{"intensity": 4, "spicy": 3}'::jsonb),
('poivre-voatsiperifery', 'Poivre voatsiperifery', 'Voatsiperifery pepper', true, ARRAY['piquant', 'africain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('reglisse-moulue', 'Réglisse moulue', 'Ground licorice', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('rooibos-epice', 'Rooibos épicé', 'Spiced rooibos', true, ARRAY['doux', 'melange', 'africain'], '{"intensity": 2, "spicy": 0}'::jsonb),
('safran-inde-frais', 'Safran d''Inde frais', 'Fresh turmeric', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('sarawak-blanc', 'Sarawak blanc', 'White Sarawak pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 3, "spicy": 2}'::jsonb),
('sauge-sechee', 'Sauge séchée', 'Dried sage', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('shichimi-togarashi', 'Shichimi togarashi', 'Shichimi togarashi', true, ARRAY['piquant', 'melange', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('sureau-moulu', 'Sureau moulu', 'Ground elderberry', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('tandoori-masala', 'Tandoori masala', 'Tandoori masala', true, ARRAY['piquant', 'melange', 'indien'], '{"intensity": 4, "spicy": 3}'::jsonb),
('thym-citron', 'Thym citron', 'Lemon thyme', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('vanille-fumee', 'Vanille fumée', 'Smoked vanilla', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  categories = EXCLUDED.categories,
  taste_profile = EXCLUDED.taste_profile,
  is_published = EXCLUDED.is_published;

-- Afficher le nombre d'épices
SELECT COUNT(*) as total_spices FROM spices WHERE is_published = true;
