-- ============================================================
-- Import batch 5 d'épices pour La Route des Épices
-- 80 épices essentielles avec noms FR/EN
-- ============================================================

INSERT INTO spices (slug, name_fr, name_en, is_published, categories, taste_profile) VALUES
('ail', 'Ail', 'Garlic', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('ail-noir', 'Ail noir', 'Black garlic', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('ail-fume', 'Ail fumé', 'Smoked garlic', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb),
('ajowan', 'Ajowan', 'Ajwain', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('amchoor', 'Amchoor', 'Dried mango powder', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('aneth-graines', 'Aneth (graines)', 'Dill seeds', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('anis-vert', 'Anis vert', 'Green anise', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('anis-etoile', 'Anis étoilé', 'Star anise', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('asafoetida', 'Asafoetida', 'Asafoetida', true, ARRAY['doux', 'indien'], '{"intensity": 5, "spicy": 0}'::jsonb),
('baie-genievre', 'Baie de genièvre', 'Juniper berry', true, ARRAY['doux', 'nordique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('baie-rose', 'Baie rose', 'Pink peppercorn', true, ARRAY['doux'], '{"intensity": 2, "spicy": 1}'::jsonb),
('basilic-seche', 'Basilic séché', 'Dried basil', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('boldo', 'Boldo', 'Boldo', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cannelle-ceylan', 'Cannelle de Ceylan', 'Ceylon cinnamon', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cannelle-cassia', 'Cannelle Cassia', 'Cassia cinnamon', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cardamome-verte', 'Cardamome verte', 'Green cardamom', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cardamome-noire', 'Cardamome noire', 'Black cardamom', true, ARRAY['doux', 'fume', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('carvi', 'Carvi', 'Caraway', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('celeri-graines', 'Céleri (graines)', 'Celery seed', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cerfeuil-seche', 'Cerfeuil séché', 'Dried chervil', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 2, "spicy": 0}'::jsonb),
('chili', 'Chili', 'Chili', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 4}'::jsonb),
('chipotle', 'Chipotle', 'Chipotle chili', true, ARRAY['piquant', 'fume', 'mexicain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('ciboulette-sechee', 'Ciboulette séchée', 'Dried chives', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('clou-girofle', 'Clou de girofle', 'Clove', true, ARRAY['doux'], '{"intensity": 5, "spicy": 0}'::jsonb),
('coriandre-graines', 'Coriandre (graines)', 'Coriander seed', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('coriandre-moulue', 'Coriandre moulue', 'Ground coriander', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cubebe', 'Cubèbe', 'Cubeb pepper', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 2}'::jsonb),
('cumin', 'Cumin', 'Cumin', true, ARRAY['doux', 'indien', 'moyen-orient'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cumin-noir', 'Cumin noir', 'Black cumin', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('curcuma', 'Curcuma', 'Turmeric', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenouil-graines', 'Fenouil (graines)', 'Fennel seed', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenugrec', 'Fenugrec', 'Fenugreek', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('galanga', 'Galanga', 'Galangal', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 1}'::jsonb),
('garam-masala', 'Garam masala', 'Garam masala', true, ARRAY['doux', 'melange', 'indien'], '{"intensity": 4, "spicy": 1}'::jsonb),
('gingembre', 'Gingembre', 'Ginger', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('gingembre-moulu', 'Gingembre moulu', 'Ground ginger', true, ARRAY['piquant', 'asiatique'], '{"intensity": 3, "spicy": 1}'::jsonb),
('graines-moutarde-jaune', 'Graines de moutarde jaune', 'Yellow mustard seed', true, ARRAY['piquant'], '{"intensity": 2, "spicy": 1}'::jsonb),
('graines-moutarde-noire', 'Graines de moutarde noire', 'Black mustard seed', true, ARRAY['piquant', 'indien'], '{"intensity": 3, "spicy": 2}'::jsonb),
('graines-nigelle', 'Graines de nigelle', 'Nigella seed', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-pavot', 'Graines de pavot', 'Poppy seed', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('graines-sesame-blanc', 'Graines de sésame blanc', 'White sesame seed', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-sesame-noir', 'Graines de sésame noir', 'Black sesame seed', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('herbes-provence', 'Herbes de Provence', 'Herbs de Provence', true, ARRAY['doux', 'melange', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('hibiscus', 'Hibiscus', 'Hibiscus', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('jalapeno-seche', 'Jalapeño séché', 'Dried jalapeño', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('laurier', 'Laurier', 'Bay leaf', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('lavande-culinaire', 'Lavande culinaire', 'Culinary lavender', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('macis', 'Macis', 'Mace', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('mahlep', 'Mahlep', 'Mahleb', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('maniguette', 'Maniguette', 'Grains of paradise', true, ARRAY['piquant', 'africain'], '{"intensity": 4, "spicy": 2}'::jsonb),
('marjolaine', 'Marjolaine', 'Marjoram', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('menthe-sechee', 'Menthe séchée', 'Dried mint', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('muscade', 'Muscade', 'Nutmeg', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('origan', 'Origan', 'Oregano', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('paprika-doux', 'Paprika doux', 'Sweet paprika', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 2, "spicy": 0}'::jsonb),
('paprika-fume', 'Paprika fumé', 'Smoked paprika', true, ARRAY['doux', 'fume', 'mediterraneen'], '{"intensity": 3, "spicy": 1}'::jsonb),
('paprika-fort', 'Paprika fort', 'Hot paprika', true, ARRAY['piquant', 'mediterraneen'], '{"intensity": 4, "spicy": 3}'::jsonb),
('persil-seche', 'Persil séché', 'Dried parsley', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 2, "spicy": 0}'::jsonb),
('piment-espelette', 'Piment d''Espelette', 'Espelette pepper', true, ARRAY['piquant', 'mediterraneen'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-cayenne', 'Piment de Cayenne', 'Cayenne pepper', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 4}'::jsonb),
('piment-ancho', 'Piment ancho', 'Ancho chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-guajillo', 'Piment guajillo', 'Guajillo chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-habanero', 'Piment habanero', 'Habanero chili', true, ARRAY['piquant', 'mexicain', 'caraibes'], '{"intensity": 5, "spicy": 5}'::jsonb),
('piment-oiseau', 'Piment oiseau', 'Bird''s eye chili', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 4}'::jsonb),
('poivre-blanc', 'Poivre blanc', 'White pepper', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('poivre-noir', 'Poivre noir', 'Black pepper', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('poivre-long', 'Poivre long', 'Long pepper', true, ARRAY['piquant', 'indien'], '{"intensity": 4, "spicy": 3}'::jsonb),
('poivre-vert', 'Poivre vert', 'Green peppercorn', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('poivre-sichuan', 'Poivre de Sichuan', 'Sichuan pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-timut', 'Poivre de Timut', 'Timut pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('ras-el-hanout', 'Ras el hanout', 'Ras el hanout', true, ARRAY['doux', 'melange', 'moyen-orient'], '{"intensity": 4, "spicy": 1}'::jsonb),
('romarin', 'Romarin', 'Rosemary', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('safran', 'Safran', 'Saffron', true, ARRAY['doux', 'mediterraneen', 'moyen-orient'], '{"intensity": 5, "spicy": 0}'::jsonb),
('sarriette', 'Sarriette', 'Savory', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('sumac', 'Sumac', 'Sumac', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('tamarin', 'Tamarin', 'Tamarind', true, ARRAY['doux', 'asiatique', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('thym', 'Thym', 'Thyme', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('vanille', 'Vanille', 'Vanilla', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('wasabi-poudre', 'Wasabi (poudre)', 'Wasabi powder', true, ARRAY['piquant', 'asiatique'], '{"intensity": 5, "spicy": 4}'::jsonb),
('zaatar', 'Za''atar', 'Zaatar', true, ARRAY['doux', 'melange', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  categories = EXCLUDED.categories,
  taste_profile = EXCLUDED.taste_profile,
  is_published = EXCLUDED.is_published;

-- Afficher le nombre d'épices
SELECT COUNT(*) as total_spices FROM spices WHERE is_published = true;
