-- ============================================================
-- Import batch 2 d'épices pour La Route des Épices
-- 80 épices avec noms FR/EN
-- ============================================================

INSERT INTO spices (slug, name_fr, name_en, is_published, categories, taste_profile) VALUES
('achiote-moulu', 'Achiote moulu', 'Ground annatto', true, ARRAY['doux', 'mexicain'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ail-granule', 'Ail granulé', 'Granulated garlic', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ail-en-poudre', 'Ail en poudre', 'Garlic powder', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('anis-sauvage', 'Anis sauvage', 'Wild anise', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('armoise', 'Armoise', 'Mugwort', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('asclepiade-sechee', 'Asclépiade séchée', 'Milkweed spice', true, ARRAY['doux', 'nordique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-acai-sechee', 'Baie d''açaï séchée', 'Dried acai berry', true, ARRAY['doux', 'bresilien'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-maqui', 'Baie de maqui', 'Maqui berry', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-poivre-sauvage', 'Baie de poivre sauvage', 'Wild pepper berry', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('baie-nepal', 'Baie du Népal', 'Nepal pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('basilic-citronne', 'Basilic citronné', 'Lemon basil', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('basilic-thai-seche', 'Basilic thaï séché', 'Dried Thai basil', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('bois-bande', 'Bois bandé', 'Banded wood spice', true, ARRAY['doux', 'caraibes'], '{"intensity": 3, "spicy": 0}'::jsonb),
('bouton-girofle-vert', 'Bouton de girofle vert', 'Green clove bud', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cannelle-sauvage', 'Cannelle sauvage', 'Wild cinnamon', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cardamome-fumee', 'Cardamome fumée', 'Smoked cardamom', true, ARRAY['doux', 'fume', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('carvi-noir', 'Carvi noir', 'Black caraway', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cassia-entiere', 'Cassia entière', 'Whole cassia bark', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('chili-morita', 'Chili morita', 'Morita chili', true, ARRAY['piquant', 'fume', 'mexicain'], '{"intensity": 4, "spicy": 4}'::jsonb),
('chili-negro', 'Chili negro', 'Negro chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('ciboule-sechee', 'Ciboule séchée', 'Dried scallion', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('citron-kaffir-seche', 'Citron kaffir séché', 'Dried kaffir lime', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('clou-girofle-sauvage', 'Clou de girofle sauvage', 'Wild clove', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('coriandre-vietnamienne', 'Coriandre vietnamienne', 'Vietnamese coriander', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cumin-blanc', 'Cumin blanc', 'White cumin', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('curcuma-fermente', 'Curcuma fermenté', 'Fermented turmeric', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ecorce-cannelle-fumee', 'Écorce de cannelle fumée', 'Smoked cinnamon bark', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb),
('ecorce-grenadier', 'Écorce de grenadier', 'Pomegranate peel', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 2, "spicy": 0}'::jsonb),
('ecorce-noyer', 'Écorce de noyer', 'Walnut bark', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('estragon-seche', 'Estragon séché', 'Dried tarragon', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenouil-doux', 'Fenouil doux', 'Sweet fennel', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenouil-marin', 'Fenouil marin', 'Sea fennel', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('feve-cacao-crue', 'Fève de cacao crue', 'Raw cacao nibs', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('fleur-jasmin-sechee', 'Fleur de jasmin séchée', 'Dried jasmine flower', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('fleur-muscade', 'Fleur de muscade', 'Nutmeg flower', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fleur-pissenlit-sechee', 'Fleur de pissenlit séchée', 'Dried dandelion flower', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('galanga-jaune', 'Galanga jaune', 'Yellow galangal', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 1}'::jsonb),
('genievre-sauvage', 'Genièvre sauvage', 'Wild juniper', true, ARRAY['doux', 'nordique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('gingembre-confit-seche', 'Gingembre confit séché', 'Dried candied ginger', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 1}'::jsonb),
('graines-anis-etoile', 'Graines d''anis étoilé', 'Star anise seeds', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('graines-bardane', 'Graines de bardane', 'Burdock seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-coriandre-verte', 'Graines de coriandre verte', 'Green coriander seed', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-melon', 'Graines de melon', 'Melon seed', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('graines-papaye', 'Graines de papaye', 'Papaya seed', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('graines-quinoa-grillees', 'Graines de quinoa grillées', 'Roasted quinoa seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-sarrasin', 'Graines de sarrasin', 'Buckwheat seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('herbe-ail', 'Herbe à ail', 'Garlic herb', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('herbe-citronnee-thaie', 'Herbe citronnée thaïe', 'Thai lemongrass', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('houblon-seche', 'Houblon séché', 'Dried hops', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('kaffir-lime-zest', 'Kaffir lime zest', 'Kaffir lime zest', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('lavande-sauvage', 'Lavande sauvage', 'Wild lavender', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('macis-fume', 'Macis fumé', 'Smoked mace', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb),
('melange-cinq-epices', 'Mélange cinq-épices chinois', 'Chinese five-spice', true, ARRAY['doux', 'melange', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('menthe-sauvage', 'Menthe sauvage', 'Wild mint', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('muscade-verte', 'Muscade verte', 'Green nutmeg', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('noix-de-galle', 'Noix de galle', 'Oak gall', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('oignon-seche', 'Oignon séché', 'Dried onion', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('oignon-en-poudre', 'Oignon en poudre', 'Onion powder', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ortie-sechee', 'Ortie séchée', 'Dried nettle', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('paprika-doux-fume', 'Paprika doux fumé', 'Smoked sweet paprika', true, ARRAY['doux', 'fume', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('paprika-piquant-fume', 'Paprika piquant fumé', 'Smoked hot paprika', true, ARRAY['piquant', 'fume', 'mediterraneen'], '{"intensity": 4, "spicy": 3}'::jsonb),
('piment-aleppo', 'Piment aleppo', 'Aleppo pepper', true, ARRAY['piquant', 'moyen-orient'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-chilhuacle', 'Piment chilhuacle', 'Chilhuacle chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('gochugaru', 'Piment coréen gochugaru', 'Gochugaru', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('piment-serrano', 'Piment serrano', 'Serrano chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 4}'::jsonb),
('poivre-citronne', 'Poivre citronné', 'Lemon pepper', true, ARRAY['doux', 'melange'], '{"intensity": 3, "spicy": 1}'::jsonb),
('poivre-fume', 'Poivre fumé', 'Smoked pepper', true, ARRAY['piquant', 'fume'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-noir-concasse', 'Poivre noir concassé', 'Cracked black pepper', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-rouge', 'Poivre rouge', 'Red peppercorn', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('racine-angelique', 'Racine d''angélique', 'Angelica root', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('racine-lotus-sechee', 'Racine de lotus séchée', 'Dried lotus root', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('reglisse-sauvage', 'Réglisse sauvage', 'Wild licorice', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('romarin-fume', 'Romarin fumé', 'Smoked rosemary', true, ARRAY['doux', 'fume', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('safran-sauvage', 'Safran sauvage', 'Wild saffron', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('sauge-blanche', 'Sauge blanche', 'White sage', true, ARRAY['doux', 'americain'], '{"intensity": 4, "spicy": 0}'::jsonb),
('shiso-seche', 'Shiso séché', 'Dried shiso', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('tamarin-fume', 'Tamarin fumé', 'Smoked tamarind', true, ARRAY['doux', 'fume', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('the-noir-epice', 'Thé noir épicé', 'Spiced black tea', true, ARRAY['doux', 'melange'], '{"intensity": 3, "spicy": 0}'::jsonb),
('thym-sauvage', 'Thym sauvage', 'Wild thyme', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('vanille-tahiti', 'Vanille de Tahiti', 'Tahitian vanilla', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  categories = EXCLUDED.categories,
  taste_profile = EXCLUDED.taste_profile,
  is_published = EXCLUDED.is_published;

-- Afficher le nombre d'épices
SELECT COUNT(*) as total_spices FROM spices WHERE is_published = true;
