-- ============================================================
-- Import COMPLET de toutes les épices pour La Route des Épices
-- 423 épices uniques avec noms FR/EN
-- ============================================================

-- Batch 1: 86 épices (rares et spécialisées)
INSERT INTO spices (slug, name_fr, name_en, is_published, categories, taste_profile) VALUES
('ail-roti-seche', 'Ail rôti séché', 'Roasted garlic', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ail-sauvage', 'Ail sauvage', 'Wild garlic', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('anis-des-montagnes', 'Anis des montagnes', 'Mountain anise', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('argousier-baies-sechees', 'Argousier (baies séchées)', 'Sea buckthorn berry', true, ARRAY['doux', 'nordique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('asperule-odorante', 'Aspérule odorante', 'Sweet woodruff', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-eglantier', 'Baie d''églantier', 'Rose hip', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-sureau-sechee', 'Baie de sureau séchée', 'Dried elderberry', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-sichuan-verte', 'Baie du Sichuan verte', 'Green Sichuan pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('basilic-africain', 'Basilic africain', 'African basil', true, ARRAY['doux', 'africain'], '{"intensity": 3, "spicy": 0}'::jsonb),
('basilic-pourpre', 'Basilic pourpre', 'Purple basil', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('bois-reglisse', 'Bois de réglisse', 'Licorice wood', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('bouton-jasmin', 'Bouton de jasmin', 'Jasmine bud', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('cannelle-saigon', 'Cannelle de Saigon', 'Saigon cinnamon', true, ARRAY['doux', 'asiatique'], '{"intensity": 5, "spicy": 0}'::jsonb),
('cannelle-fumee', 'Cannelle fumée', 'Smoked cinnamon', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cardamome-ethiopie', 'Cardamome d''Éthiopie', 'Ethiopian cardamom', true, ARRAY['doux', 'africain'], '{"intensity": 4, "spicy": 0}'::jsonb),
('carvi-brun', 'Carvi brun', 'Brown caraway', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cassis-seche', 'Cassis séché', 'Dried blackcurrant', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('cerfeuil-sauvage', 'Cerfeuil sauvage', 'Wild chervil', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 2, "spicy": 0}'::jsonb),
('chili-chiltepin', 'Chili chiltepin', 'Chiltepin chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 5}'::jsonb),
('chili-ghost', 'Chili ghost (bhut jolokia)', 'Ghost pepper', true, ARRAY['piquant', 'indien'], '{"intensity": 5, "spicy": 5}'::jsonb),
('chili-scorpion', 'Chili scorpion', 'Scorpion pepper', true, ARRAY['piquant', 'caraibes'], '{"intensity": 5, "spicy": 5}'::jsonb),
('ciboulette-chinoise', 'Ciboulette chinoise', 'Chinese chives', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('citron-caviar-seche', 'Citron caviar séché', 'Dried finger lime', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('clou-girofle-rose', 'Clou de girofle rose', 'Pink clove', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('coriandre-longue', 'Coriandre longue', 'Long coriander', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cumin-royal', 'Cumin royal', 'Royal cumin', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('curcuma-fume', 'Curcuma fumé', 'Smoked turmeric', true, ARRAY['doux', 'fume', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ecorce-bouleau', 'Écorce de bouleau', 'Birch bark spice', true, ARRAY['doux', 'nordique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('ecorce-cannelle-verte', 'Écorce de cannelle verte', 'Green cinnamon bark', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ecorce-mangoustan', 'Écorce de mangoustan', 'Mangosteen rind', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('estragon-mexicain', 'Estragon mexicain', 'Mexican tarragon', true, ARRAY['doux', 'mexicain'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenouil-indien', 'Fenouil indien', 'Indian fennel', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenugrec-germe-seche', 'Fenugrec germé séché', 'Sprouted fenugreek', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('feve-tonka-rapee', 'Fève tonka râpée', 'Grated tonka bean', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('fleur-oranger-sechee', 'Fleur d''oranger séchée', 'Dried orange blossom', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 2, "spicy": 0}'::jsonb),
('fleur-coriandre', 'Fleur de coriandre', 'Coriander flower', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('fleur-thym', 'Fleur de thym', 'Thyme flower', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('galanga-fume', 'Galanga fumé', 'Smoked galangal', true, ARRAY['doux', 'fume', 'asiatique'], '{"intensity": 4, "spicy": 1}'::jsonb),
('genievre-rouge', 'Genièvre rouge', 'Red juniper berry', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('gingembre-noir', 'Gingembre noir', 'Black ginger', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('graines-aneth-moulues', 'Graines d''aneth moulues', 'Ground dill seed', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-basilic', 'Graines de basilic', 'Basil seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-chanvre', 'Graines de chanvre', 'Hemp seed', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('graines-chia', 'Graines de chia', 'Chia seed', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('graines-moutarde-sauvage', 'Graines de moutarde sauvage', 'Wild mustard seed', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('graines-nigelle-sauvage', 'Graines de nigelle sauvage', 'Wild nigella seed', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-poivre-rose-moulues', 'Graines de poivre rose moulues', 'Ground pink peppercorn', true, ARRAY['doux'], '{"intensity": 2, "spicy": 1}'::jsonb),
('graines-sesame-grillees', 'Graines de sésame grillées', 'Toasted sesame seed', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('herbe-tigre', 'Herbe du tigre', 'Tiger grass', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('hysope-anisee', 'Hysope anisée', 'Anise hyssop', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('kaffir-lime-entier-seche', 'Kaffir lime entier séché', 'Whole dried kaffir lime', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('laurier-indien', 'Laurier indien', 'Indian bay leaf', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('liveche-sauvage', 'Livèche sauvage', 'Wild lovage', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('macis-sauvage', 'Macis sauvage', 'Wild mace', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('melange-barbecue-epice', 'Mélange barbecue épicé', 'Spicy barbecue rub', true, ARRAY['piquant', 'melange', 'americain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('melange-cajun', 'Mélange cajun', 'Cajun spice mix', true, ARRAY['piquant', 'melange', 'americain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('melange-creole', 'Mélange créole', 'Creole spice blend', true, ARRAY['piquant', 'melange', 'caraibes'], '{"intensity": 3, "spicy": 2}'::jsonb),
('dukkah', 'Mélange dukkah', 'Dukkah', true, ARRAY['doux', 'melange', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('melange-jerk', 'Mélange jerk', 'Jerk seasoning', true, ARRAY['piquant', 'melange', 'caraibes'], '{"intensity": 4, "spicy": 4}'::jsonb),
('menthe-chocolat', 'Menthe chocolat', 'Chocolate mint', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('muscade-fumee', 'Muscade fumée', 'Smoked nutmeg', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb),
('oignon-roti-seche', 'Oignon rôti séché', 'Roasted dried onion', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('origan-grec', 'Origan grec', 'Greek oregano', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('paprika-noir', 'Paprika noir', 'Black paprika', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 1}'::jsonb),
('piment-carolina-reaper', 'Piment carolina reaper', 'Carolina Reaper', true, ARRAY['piquant', 'americain'], '{"intensity": 5, "spicy": 5}'::jsonb),
('piment-jamaicain-fume', 'Piment jamaïcain fumé', 'Smoked allspice', true, ARRAY['doux', 'fume', 'caraibes'], '{"intensity": 4, "spicy": 0}'::jsonb),
('poivre-andaliman', 'Poivre andaliman', 'Andaliman pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-cubebe-fume', 'Poivre de Cubèbe fumé', 'Smoked cubeb pepper', true, ARRAY['piquant', 'fume'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-java', 'Poivre de Java', 'Java pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('poivre-tasmanie', 'Poivre de Tasmanie', 'Tasmanian pepperberry', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 3}'::jsonb),
('poivre-sauvage-africain', 'Poivre sauvage africain', 'African wild pepper', true, ARRAY['piquant', 'africain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('racine-curcuma-sechee', 'Racine de curcuma séchée', 'Dried turmeric root', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('racine-gingembre-fumee', 'Racine de gingembre fumée', 'Smoked ginger root', true, ARRAY['piquant', 'fume'], '{"intensity": 4, "spicy": 2}'::jsonb),
('reglisse-etoilee', 'Réglisse étoilée', 'Star licorice', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('romarin-sauvage', 'Romarin sauvage', 'Wild rosemary', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('safran-espagnol', 'Safran espagnol', 'Spanish saffron', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 5, "spicy": 0}'::jsonb),
('safran-iranien', 'Safran iranien', 'Iranian saffron', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 5, "spicy": 0}'::jsonb),
('sarriette-ete', 'Sarriette d''été', 'Summer savory', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('sarriette-hiver', 'Sarriette d''hiver', 'Winter savory', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('shiso-pourpre', 'Shiso pourpre', 'Purple shiso', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('sumac-fume', 'Sumac fumé', 'Smoked sumac', true, ARRAY['doux', 'fume', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('tamarin-concentre', 'Tamarin concentré', 'Tamarind concentrate', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('thym-fume', 'Thym fumé', 'Smoked thyme', true, ARRAY['doux', 'fume', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('vanille-bourbon', 'Vanille bourbon', 'Bourbon vanilla', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('vanille-mexicaine', 'Vanille mexicaine', 'Mexican vanilla', true, ARRAY['doux', 'mexicain'], '{"intensity": 4, "spicy": 0}'::jsonb),
('zeste-yuzu-seche', 'Zeste de yuzu séché', 'Dried yuzu zest', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  categories = EXCLUDED.categories,
  taste_profile = EXCLUDED.taste_profile,
  is_published = EXCLUDED.is_published;

-- Batch 2: 80 épices
INSERT INTO spices (slug, name_fr, name_en, is_published, categories, taste_profile) VALUES
('achiote-moulu', 'Achiote moulu', 'Ground annatto', true, ARRAY['doux', 'mexicain'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ail-granule', 'Ail granulé', 'Granulated garlic', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ail-en-poudre', 'Ail en poudre', 'Garlic powder', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('anis-sauvage', 'Anis sauvage', 'Wild anise', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('armoise', 'Armoise', 'Mugwort', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('asclepiade-sechee', 'Asclépiade séchée', 'Milkweed spice', true, ARRAY['doux', 'nordique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-acai-sechee', 'Baie d''açaï séchée', 'Dried acai berry', true, ARRAY['doux', 'bresilien'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-maqui', 'Baie de maqui', 'Maqui berry', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('baie-poivre-sauvage', 'Baie de poivre sauvage', 'Wild pepper berry', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('baie-nepal', 'Baie du Népal', 'Nepal pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('basilic-citronne', 'Basilic citronné', 'Lemon basil', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('basilic-thai-seche', 'Basilic thaï séché', 'Dried Thai basil', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('bois-bande', 'Bois bandé', 'Banded wood spice', true, ARRAY['doux', 'caraibes'], '{"intensity": 3, "spicy": 0}'::jsonb),
('bouton-girofle-vert', 'Bouton de girofle vert', 'Green clove bud', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cannelle-sauvage', 'Cannelle sauvage', 'Wild cinnamon', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cardamome-fumee', 'Cardamome fumée', 'Smoked cardamom', true, ARRAY['doux', 'fume', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('carvi-noir', 'Carvi noir', 'Black caraway', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cassia-entiere', 'Cassia entière', 'Whole cassia bark', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('chili-morita', 'Chili morita', 'Morita chili', true, ARRAY['piquant', 'fume', 'mexicain'], '{"intensity": 4, "spicy": 4}'::jsonb),
('chili-negro', 'Chili negro', 'Negro chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('ciboule-sechee', 'Ciboule séchée', 'Dried scallion', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('citron-kaffir-seche', 'Citron kaffir séché', 'Dried kaffir lime', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('clou-girofle-sauvage', 'Clou de girofle sauvage', 'Wild clove', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('coriandre-vietnamienne', 'Coriandre vietnamienne', 'Vietnamese coriander', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cumin-blanc', 'Cumin blanc', 'White cumin', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('curcuma-fermente', 'Curcuma fermenté', 'Fermented turmeric', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ecorce-cannelle-fumee', 'Écorce de cannelle fumée', 'Smoked cinnamon bark', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb),
('ecorce-grenadier', 'Écorce de grenadier', 'Pomegranate peel', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 2, "spicy": 0}'::jsonb),
('ecorce-noyer', 'Écorce de noyer', 'Walnut bark', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('estragon-seche', 'Estragon séché', 'Dried tarragon', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenouil-doux', 'Fenouil doux', 'Sweet fennel', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenouil-marin', 'Fenouil marin', 'Sea fennel', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('feve-cacao-crue', 'Fève de cacao crue', 'Raw cacao nibs', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('fleur-jasmin-sechee', 'Fleur de jasmin séchée', 'Dried jasmine flower', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('fleur-muscade', 'Fleur de muscade', 'Nutmeg flower', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fleur-pissenlit-sechee', 'Fleur de pissenlit séchée', 'Dried dandelion flower', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('galanga-jaune', 'Galanga jaune', 'Yellow galangal', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 1}'::jsonb),
('genievre-sauvage', 'Genièvre sauvage', 'Wild juniper', true, ARRAY['doux', 'nordique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('gingembre-confit-seche', 'Gingembre confit séché', 'Dried candied ginger', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 1}'::jsonb),
('graines-anis-etoile', 'Graines d''anis étoilé', 'Star anise seeds', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('graines-bardane', 'Graines de bardane', 'Burdock seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-coriandre-verte', 'Graines de coriandre verte', 'Green coriander seed', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-melon', 'Graines de melon', 'Melon seed', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('graines-papaye', 'Graines de papaye', 'Papaya seed', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('graines-quinoa-grillees', 'Graines de quinoa grillées', 'Roasted quinoa seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-sarrasin', 'Graines de sarrasin', 'Buckwheat seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('herbe-ail', 'Herbe à ail', 'Garlic herb', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('herbe-citronnee-thaie', 'Herbe citronnée thaïe', 'Thai lemongrass', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('houblon-seche', 'Houblon séché', 'Dried hops', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('kaffir-lime-zest', 'Kaffir lime zest', 'Kaffir lime zest', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('lavande-sauvage', 'Lavande sauvage', 'Wild lavender', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('macis-fume', 'Macis fumé', 'Smoked mace', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb),
('melange-cinq-epices', 'Mélange cinq-épices chinois', 'Chinese five-spice', true, ARRAY['doux', 'melange', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('menthe-sauvage', 'Menthe sauvage', 'Wild mint', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('muscade-verte', 'Muscade verte', 'Green nutmeg', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('noix-de-galle', 'Noix de galle', 'Oak gall', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('oignon-seche', 'Oignon séché', 'Dried onion', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('oignon-en-poudre', 'Oignon en poudre', 'Onion powder', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ortie-sechee', 'Ortie séchée', 'Dried nettle', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('paprika-doux-fume', 'Paprika doux fumé', 'Smoked sweet paprika', true, ARRAY['doux', 'fume', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('paprika-piquant-fume', 'Paprika piquant fumé', 'Smoked hot paprika', true, ARRAY['piquant', 'fume', 'mediterraneen'], '{"intensity": 4, "spicy": 3}'::jsonb),
('piment-aleppo', 'Piment aleppo', 'Aleppo pepper', true, ARRAY['piquant', 'moyen-orient'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-chilhuacle', 'Piment chilhuacle', 'Chilhuacle chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('gochugaru', 'Piment coréen gochugaru', 'Gochugaru', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('piment-serrano', 'Piment serrano', 'Serrano chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 4}'::jsonb),
('poivre-citronne', 'Poivre citronné', 'Lemon pepper', true, ARRAY['doux', 'melange'], '{"intensity": 3, "spicy": 1}'::jsonb),
('poivre-fume', 'Poivre fumé', 'Smoked pepper', true, ARRAY['piquant', 'fume'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-noir-concasse', 'Poivre noir concassé', 'Cracked black pepper', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-rouge', 'Poivre rouge', 'Red peppercorn', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('racine-angelique', 'Racine d''angélique', 'Angelica root', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('racine-lotus-sechee', 'Racine de lotus séchée', 'Dried lotus root', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('reglisse-sauvage', 'Réglisse sauvage', 'Wild licorice', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('romarin-fume', 'Romarin fumé', 'Smoked rosemary', true, ARRAY['doux', 'fume', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('safran-sauvage', 'Safran sauvage', 'Wild saffron', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('sauge-blanche', 'Sauge blanche', 'White sage', true, ARRAY['doux', 'americain'], '{"intensity": 4, "spicy": 0}'::jsonb),
('shiso-seche', 'Shiso séché', 'Dried shiso', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('tamarin-fume', 'Tamarin fumé', 'Smoked tamarind', true, ARRAY['doux', 'fume', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('the-noir-epice', 'Thé noir épicé', 'Spiced black tea', true, ARRAY['doux', 'melange'], '{"intensity": 3, "spicy": 0}'::jsonb),
('thym-sauvage', 'Thym sauvage', 'Wild thyme', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('vanille-tahiti', 'Vanille de Tahiti', 'Tahitian vanilla', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  categories = EXCLUDED.categories,
  taste_profile = EXCLUDED.taste_profile,
  is_published = EXCLUDED.is_published;

-- Batch 3: 91 épices
INSERT INTO spices (slug, name_fr, name_en, is_published, categories, taste_profile) VALUES
('achiote-roucou', 'Achiote (roucou)', 'Annatto seed', true, ARRAY['doux', 'mexicain', 'caraibes'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ail-des-ours-seche', 'Ail des ours séché', 'Wild garlic', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('anis-bleu', 'Anis bleu', 'Blue anise', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('arbre-curry-graines', 'Arbre à curry (graines)', 'Curry tree seed', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('asaret', 'Asaret', 'Wild ginger', true, ARRAY['doux'], '{"intensity": 3, "spicy": 1}'::jsonb),
('badiane-moulue', 'Badiane moulue', 'Ground star anise', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('baie-myrte', 'Baie de myrte', 'Myrtle berry', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('baie-poivre-cubebe', 'Baie de poivre cubèbe', 'Cubeb berry', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 2}'::jsonb),
('baie-sansho', 'Baie de sansho', 'Sansho pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('basilic-sacre-tulsi', 'Basilic sacré (Tulsi)', 'Holy basil', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('berbere', 'Berbéré (mélange)', 'Berbere spice mix', true, ARRAY['piquant', 'melange', 'africain'], '{"intensity": 4, "spicy": 4}'::jsonb),
('betel-feuille-sechee', 'Bétel (feuille séchée)', 'Betel leaf', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('bhringraj', 'Bhringraj', 'False daisy', true, ARRAY['doux', 'indien'], '{"intensity": 2, "spicy": 0}'::jsonb),
('bois-inde', 'Bois d''Inde', 'Allspice', true, ARRAY['doux', 'caraibes'], '{"intensity": 4, "spicy": 0}'::jsonb),
('bouton-rose-seche', 'Bouton de rose séché', 'Dried rosebud', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 2, "spicy": 0}'::jsonb),
('bouton-cassis', 'Bouton de cassis', 'Blackcurrant bud', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('caloupile-seche', 'Caloupilé séché', 'Dried curry leaf', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('camomille', 'Camomille', 'Chamomile', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('cardamome-blanche', 'Cardamome blanche', 'White cardamom', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cardamome-chinoise', 'Cardamome chinoise', 'Chinese cardamom', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('caroube', 'Caroube', 'Carob powder', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cassia-poudre', 'Cassia en poudre', 'Ground cassia', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cedrat-seche', 'Cédrat séché', 'Dried citron peel', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('chili-arbol', 'Chili árbol', 'Arbol chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 4}'::jsonb),
('chili-pasilla', 'Chili pasilla', 'Pasilla chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('citronnelle', 'Citronnelle', 'Lemongrass', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('citron-noir-loomi', 'Citron noir (loomi)', 'Dried black lime', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 4, "spicy": 0}'::jsonb),
('clou-girofle-moulu', 'Clou de girofle moulu', 'Ground clove', true, ARRAY['doux'], '{"intensity": 5, "spicy": 0}'::jsonb),
('coriandre-racine', 'Coriandre racine', 'Coriander root', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cresson-alenois-graines', 'Cresson alénois (graines)', 'Garden cress seed', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('cumin-des-pres', 'Cumin des prés', 'Meadow cumin', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cumin-vert', 'Cumin vert', 'Green cumin', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('curcuma-blanc', 'Curcuma blanc', 'White turmeric', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('curcuma-noir', 'Curcuma noir', 'Black turmeric', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('dill-pollen', 'Dill pollen', 'Dill pollen', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ecorce-orange-amere', 'Écorce d''orange amère', 'Bitter orange peel', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('ecorce-citron', 'Écorce de citron', 'Lemon peel', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('epazote', 'Épazote', 'Epazote', true, ARRAY['doux', 'mexicain'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenugrec-moulu', 'Fenugrec moulu', 'Ground fenugreek', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('feve-calabar', 'Fève de calabar', 'Calabar bean', true, ARRAY['doux', 'africain'], '{"intensity": 2, "spicy": 0}'::jsonb),
('feuille-combava-sechee', 'Feuille de combava séchée', 'Dried kaffir lime leaf', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('fleur-bananier-sechee', 'Fleur de bananier séchée', 'Dried banana blossom', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('fleur-cannelle', 'Fleur de cannelle', 'Cinnamon flower', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fleur-sel-epicee', 'Fleur de sel épicée', 'Spiced sea salt', true, ARRAY['doux', 'melange'], '{"intensity": 2, "spicy": 0}'::jsonb),
('fleur-sureau', 'Fleur de sureau', 'Elderflower', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('galanga-rouge', 'Galanga rouge', 'Red galangal', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('genievre-moulu', 'Genièvre moulu', 'Ground juniper', true, ARRAY['doux', 'nordique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('gingembre-sauvage', 'Gingembre sauvage', 'Wild ginger', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 2}'::jsonb),
('graines-angelique', 'Graines d''angélique', 'Angelica seed', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-carotte', 'Graines de carotte', 'Carrot seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-cumin-noir', 'Graines de cumin noir', 'Black cumin seed', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('graines-fenouil-sauvage', 'Graines de fenouil sauvage', 'Wild fennel seed', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-lin', 'Graines de lin', 'Flaxseed', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('graines-moutarde-brune', 'Graines de moutarde brune', 'Brown mustard seed', true, ARRAY['piquant', 'indien'], '{"intensity": 3, "spicy": 2}'::jsonb),
('graines-roquette', 'Graines de roquette', 'Arugula seed', true, ARRAY['piquant'], '{"intensity": 2, "spicy": 1}'::jsonb),
('graines-sene', 'Graines de séné', 'Senna seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-tournesol-grillees', 'Graines de tournesol grillées', 'Roasted sunflower seed', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('herbe-curry', 'Herbe à curry', 'Curry herb', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('hysope', 'Hysope', 'Hyssop', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('kaloupile-moulu', 'Kaloupilé moulu', 'Ground curry leaf', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('kencur', 'Kencur', 'Aromatic ginger', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 1}'::jsonb),
('lime-sechee', 'Lime séchée', 'Dried lime', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('liveche', 'Livèche', 'Lovage', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('macis-moulu', 'Macis moulu', 'Ground mace', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('mandarine-sechee', 'Mandarine séchée', 'Dried mandarin peel', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('melilot', 'Mélilot', 'Sweet clover', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('menthe-poivree-sechee', 'Menthe poivrée séchée', 'Dried peppermint', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('moutarde-verte', 'Moutarde verte', 'Green mustard', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('nigelle-moulue', 'Nigelle moulue', 'Ground nigella', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('noix-kola', 'Noix de kola', 'Kola nut', true, ARRAY['doux', 'africain'], '{"intensity": 3, "spicy": 0}'::jsonb),
('noix-muscade-longue', 'Noix muscade longue', 'Long nutmeg', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('origan-mexicain', 'Origan mexicain', 'Mexican oregano', true, ARRAY['doux', 'mexicain'], '{"intensity": 4, "spicy": 0}'::jsonb),
('paprika-espagnol', 'Paprika espagnol', 'Spanish paprika', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 1}'::jsonb),
('paprika-hongrois', 'Paprika hongrois', 'Hungarian paprika', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 1}'::jsonb),
('piment-cascabel', 'Piment cascabel', 'Cascabel chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-mulato', 'Piment mulato', 'Mulato chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-piquin', 'Piment piquín', 'Pequin chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 5}'::jsonb),
('poivre-kampot', 'Poivre de Kampot', 'Kampot pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('poivre-sarawak', 'Poivre de Sarawak', 'Sarawak pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-tellicherry', 'Poivre de Tellicherry', 'Tellicherry pepper', true, ARRAY['piquant', 'indien'], '{"intensity": 4, "spicy": 3}'::jsonb),
('poivre-voatsiperifery', 'Poivre voatsiperifery', 'Voatsiperifery pepper', true, ARRAY['piquant', 'africain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('reglisse-moulue', 'Réglisse moulue', 'Ground licorice', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('rooibos-epice', 'Rooibos épicé', 'Spiced rooibos', true, ARRAY['doux', 'melange', 'africain'], '{"intensity": 2, "spicy": 0}'::jsonb),
('safran-inde-frais', 'Safran d''Inde frais', 'Fresh turmeric', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('sarawak-blanc', 'Sarawak blanc', 'White Sarawak pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 3, "spicy": 2}'::jsonb),
('sauge-sechee', 'Sauge séchée', 'Dried sage', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('shichimi-togarashi', 'Shichimi togarashi', 'Shichimi togarashi', true, ARRAY['piquant', 'melange', 'asiatique'], '{"intensity": 4, "spicy": 3}'::jsonb),
('sureau-moulu', 'Sureau moulu', 'Ground elderberry', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('tandoori-masala', 'Tandoori masala', 'Tandoori masala', true, ARRAY['piquant', 'melange', 'indien'], '{"intensity": 4, "spicy": 3}'::jsonb),
('thym-citron', 'Thym citron', 'Lemon thyme', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('vanille-fumee', 'Vanille fumée', 'Smoked vanilla', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  categories = EXCLUDED.categories,
  taste_profile = EXCLUDED.taste_profile,
  is_published = EXCLUDED.is_published;

-- Batch 4: 80 épices essentielles
INSERT INTO spices (slug, name_fr, name_en, is_published, categories, taste_profile) VALUES
('ail', 'Ail', 'Garlic', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('ail-noir', 'Ail noir', 'Black garlic', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('ail-fume', 'Ail fumé', 'Smoked garlic', true, ARRAY['doux', 'fume'], '{"intensity": 4, "spicy": 0}'::jsonb),
('ajowan', 'Ajowan', 'Ajwain', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('amchoor', 'Amchoor', 'Dried mango powder', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('aneth-graines', 'Aneth (graines)', 'Dill seeds', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('anis-vert', 'Anis vert', 'Green anise', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('anis-etoile', 'Anis étoilé', 'Star anise', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('asafoetida', 'Asafoetida', 'Asafoetida', true, ARRAY['doux', 'indien'], '{"intensity": 5, "spicy": 0}'::jsonb),
('baie-genievre', 'Baie de genièvre', 'Juniper berry', true, ARRAY['doux', 'nordique'], '{"intensity": 3, "spicy": 0}'::jsonb),
('baie-rose', 'Baie rose', 'Pink peppercorn', true, ARRAY['doux'], '{"intensity": 2, "spicy": 1}'::jsonb),
('basilic-seche', 'Basilic séché', 'Dried basil', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('boldo', 'Boldo', 'Boldo', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cannelle-ceylan', 'Cannelle de Ceylan', 'Ceylon cinnamon', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cannelle-cassia', 'Cannelle Cassia', 'Cassia cinnamon', true, ARRAY['doux', 'asiatique'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cardamome-verte', 'Cardamome verte', 'Green cardamom', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cardamome-noire', 'Cardamome noire', 'Black cardamom', true, ARRAY['doux', 'fume', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('carvi', 'Carvi', 'Caraway', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('celeri-graines', 'Céleri (graines)', 'Celery seed', true, ARRAY['doux'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cerfeuil-seche', 'Cerfeuil séché', 'Dried chervil', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 2, "spicy": 0}'::jsonb),
('chili', 'Chili', 'Chili', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 4}'::jsonb),
('chipotle', 'Chipotle', 'Chipotle chili', true, ARRAY['piquant', 'fume', 'mexicain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('ciboulette-sechee', 'Ciboulette séchée', 'Dried chives', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('clou-girofle', 'Clou de girofle', 'Clove', true, ARRAY['doux'], '{"intensity": 5, "spicy": 0}'::jsonb),
('coriandre-graines', 'Coriandre (graines)', 'Coriander seed', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('coriandre-moulue', 'Coriandre moulue', 'Ground coriander', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('cubebe', 'Cubèbe', 'Cubeb pepper', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 2}'::jsonb),
('cumin', 'Cumin', 'Cumin', true, ARRAY['doux', 'indien', 'moyen-orient'], '{"intensity": 4, "spicy": 0}'::jsonb),
('cumin-noir', 'Cumin noir', 'Black cumin', true, ARRAY['doux', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('curcuma', 'Curcuma', 'Turmeric', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenouil-graines', 'Fenouil (graines)', 'Fennel seed', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('fenugrec', 'Fenugrec', 'Fenugreek', true, ARRAY['doux', 'indien'], '{"intensity": 3, "spicy": 0}'::jsonb),
('galanga', 'Galanga', 'Galangal', true, ARRAY['doux', 'asiatique'], '{"intensity": 3, "spicy": 1}'::jsonb),
('garam-masala', 'Garam masala', 'Garam masala', true, ARRAY['doux', 'melange', 'indien'], '{"intensity": 4, "spicy": 1}'::jsonb),
('gingembre', 'Gingembre', 'Ginger', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('gingembre-moulu', 'Gingembre moulu', 'Ground ginger', true, ARRAY['piquant', 'asiatique'], '{"intensity": 3, "spicy": 1}'::jsonb),
('graines-moutarde-jaune', 'Graines de moutarde jaune', 'Yellow mustard seed', true, ARRAY['piquant'], '{"intensity": 2, "spicy": 1}'::jsonb),
('graines-moutarde-noire', 'Graines de moutarde noire', 'Black mustard seed', true, ARRAY['piquant', 'indien'], '{"intensity": 3, "spicy": 2}'::jsonb),
('graines-nigelle', 'Graines de nigelle', 'Nigella seed', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('graines-pavot', 'Graines de pavot', 'Poppy seed', true, ARRAY['doux'], '{"intensity": 1, "spicy": 0}'::jsonb),
('graines-sesame-blanc', 'Graines de sésame blanc', 'White sesame seed', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('graines-sesame-noir', 'Graines de sésame noir', 'Black sesame seed', true, ARRAY['doux', 'asiatique'], '{"intensity": 2, "spicy": 0}'::jsonb),
('herbes-provence', 'Herbes de Provence', 'Herbs de Provence', true, ARRAY['doux', 'melange', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('hibiscus', 'Hibiscus', 'Hibiscus', true, ARRAY['doux'], '{"intensity": 2, "spicy": 0}'::jsonb),
('jalapeno-seche', 'Jalapeño séché', 'Dried jalapeño', true, ARRAY['piquant', 'mexicain'], '{"intensity": 4, "spicy": 3}'::jsonb),
('laurier', 'Laurier', 'Bay leaf', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('lavande-culinaire', 'Lavande culinaire', 'Culinary lavender', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('macis', 'Macis', 'Mace', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('mahlep', 'Mahlep', 'Mahleb', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('maniguette', 'Maniguette', 'Grains of paradise', true, ARRAY['piquant', 'africain'], '{"intensity": 4, "spicy": 2}'::jsonb),
('marjolaine', 'Marjolaine', 'Marjoram', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('menthe-sechee', 'Menthe séchée', 'Dried mint', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('muscade', 'Muscade', 'Nutmeg', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('origan', 'Origan', 'Oregano', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('paprika-doux', 'Paprika doux', 'Sweet paprika', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 2, "spicy": 0}'::jsonb),
('paprika-fume', 'Paprika fumé', 'Smoked paprika', true, ARRAY['doux', 'fume', 'mediterraneen'], '{"intensity": 3, "spicy": 1}'::jsonb),
('paprika-fort', 'Paprika fort', 'Hot paprika', true, ARRAY['piquant', 'mediterraneen'], '{"intensity": 4, "spicy": 3}'::jsonb),
('persil-seche', 'Persil séché', 'Dried parsley', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 2, "spicy": 0}'::jsonb),
('piment-espelette', 'Piment d''Espelette', 'Espelette pepper', true, ARRAY['piquant', 'mediterraneen'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-cayenne', 'Piment de Cayenne', 'Cayenne pepper', true, ARRAY['piquant'], '{"intensity": 4, "spicy": 4}'::jsonb),
('piment-ancho', 'Piment ancho', 'Ancho chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-guajillo', 'Piment guajillo', 'Guajillo chili', true, ARRAY['piquant', 'mexicain'], '{"intensity": 3, "spicy": 2}'::jsonb),
('piment-habanero', 'Piment habanero', 'Habanero chili', true, ARRAY['piquant', 'mexicain', 'caraibes'], '{"intensity": 5, "spicy": 5}'::jsonb),
('piment-oiseau', 'Piment oiseau', 'Bird''s eye chili', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 4}'::jsonb),
('poivre-blanc', 'Poivre blanc', 'White pepper', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('poivre-noir', 'Poivre noir', 'Black pepper', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('poivre-long', 'Poivre long', 'Long pepper', true, ARRAY['piquant', 'indien'], '{"intensity": 4, "spicy": 3}'::jsonb),
('poivre-vert', 'Poivre vert', 'Green peppercorn', true, ARRAY['piquant'], '{"intensity": 3, "spicy": 2}'::jsonb),
('poivre-sichuan', 'Poivre de Sichuan', 'Sichuan pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('poivre-timut', 'Poivre de Timut', 'Timut pepper', true, ARRAY['piquant', 'asiatique'], '{"intensity": 4, "spicy": 2}'::jsonb),
('ras-el-hanout', 'Ras el hanout', 'Ras el hanout', true, ARRAY['doux', 'melange', 'moyen-orient'], '{"intensity": 4, "spicy": 1}'::jsonb),
('romarin', 'Romarin', 'Rosemary', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 4, "spicy": 0}'::jsonb),
('safran', 'Safran', 'Saffron', true, ARRAY['doux', 'mediterraneen', 'moyen-orient'], '{"intensity": 5, "spicy": 0}'::jsonb),
('sarriette', 'Sarriette', 'Savory', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('sumac', 'Sumac', 'Sumac', true, ARRAY['doux', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb),
('tamarin', 'Tamarin', 'Tamarind', true, ARRAY['doux', 'asiatique', 'indien'], '{"intensity": 4, "spicy": 0}'::jsonb),
('thym', 'Thym', 'Thyme', true, ARRAY['doux', 'mediterraneen'], '{"intensity": 3, "spicy": 0}'::jsonb),
('vanille', 'Vanille', 'Vanilla', true, ARRAY['doux'], '{"intensity": 4, "spicy": 0}'::jsonb),
('wasabi-poudre', 'Wasabi (poudre)', 'Wasabi powder', true, ARRAY['piquant', 'asiatique'], '{"intensity": 5, "spicy": 4}'::jsonb),
('zaatar', 'Za''atar', 'Zaatar', true, ARRAY['doux', 'melange', 'moyen-orient'], '{"intensity": 3, "spicy": 0}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_en = EXCLUDED.name_en,
  categories = EXCLUDED.categories,
  taste_profile = EXCLUDED.taste_profile,
  is_published = EXCLUDED.is_published;

-- Afficher le nombre total d'épices
SELECT COUNT(*) as total_spices FROM spices WHERE is_published = true;
