-- ============================================================
-- Import des épices de départ pour le dictionnaire
-- À exécuter après create-spices-table.sql
-- ============================================================

-- 1. CUMIN
INSERT INTO spices (
  slug, name_fr, name_en, other_names,
  definition_fr, definition_en,
  origin, history_fr, history_en,
  taste_profile, usage_tips_fr, usage_tips_en,
  common_mistakes_fr, common_mistakes_en,
  used_with, benefits_fr, benefits_en,
  storage_fr, storage_en, substitutes,
  seo_title_fr, seo_title_en,
  seo_description_fr, seo_description_en,
  faq, categories, is_published
) VALUES (
  'cumin',
  'Cumin',
  'Cumin',
  ARRAY['Cuminum cyminum'],
  'Le cumin est une épice chaude et terreuse avec des notes légèrement amères et citronnées. Essentiel dans les cuisines du Moyen-Orient, indienne et mexicaine.',
  'Cumin is a warm, earthy spice with slightly bitter and lemony notes. Essential in Middle Eastern, Indian and Mexican cuisines.',
  ARRAY['Moyen-Orient', 'Égypte', 'Inde'],
  'Le cumin est l''une des plus anciennes épices connues, utilisée depuis plus de 5000 ans. Les Égyptiens l''utilisaient pour momifier les pharaons.',
  'Cumin is one of the oldest known spices, used for over 5000 years. Egyptians used it to mummify pharaohs.',
  '{"intensity": 4, "spicy": 1, "bitterness": 2, "sweetness": 0, "notes_fr": ["terreux", "chaud", "citronné", "légèrement amer"], "notes_en": ["earthy", "warm", "lemony", "slightly bitter"]}'::jsonb,
  '<p><strong>Comment l''utiliser:</strong></p><ul><li>Griller légèrement les graines avant utilisation pour intensifier le goût</li><li>Ajouter en début de cuisson dans l''huile chaude</li><li>Excellent moulu ou en graines entières</li></ul>',
  '<p><strong>How to use:</strong></p><ul><li>Lightly toast seeds before use to intensify flavor</li><li>Add at the beginning of cooking in hot oil</li><li>Excellent ground or as whole seeds</li></ul>',
  '<p><strong>Erreurs à éviter:</strong></p><ul><li>Ne pas brûler les graines - devient très amer</li><li>Ne pas en mettre trop - saveur dominante</li></ul>',
  '<p><strong>Mistakes to avoid:</strong></p><ul><li>Don''t burn the seeds - becomes very bitter</li><li>Don''t use too much - dominant flavor</li></ul>',
  '{"meat": ["agneau", "bœuf", "poulet"], "fish": [], "vegetables": ["carottes", "courgettes", "aubergines", "pois chiches"], "grains": ["riz", "couscous"], "bread": [], "desserts": [], "cheese": [], "soups": ["soupe de lentilles", "chili"]}'::jsonb,
  '<p>Favorise la digestion et contient du fer.</p>',
  '<p>Promotes digestion and contains iron.</p>',
  '<p>Pot hermétique, 6-12 mois moulu, 2-3 ans en graines.</p>',
  '<p>Airtight container, 6-12 months ground, 2-3 years as seeds.</p>',
  ARRAY['coriandre', 'carvi'],
  'Cumin: Épice Chaude et Terreuse | Guide Complet',
  'Cumin: Warm and Earthy Spice | Complete Guide',
  'Tout sur le cumin: origine, goût terreux, utilisations en cuisine. Indispensable pour le chili, couscous et curry.',
  'Everything about cumin: origin, earthy taste, cooking uses. Essential for chili, couscous and curry.',
  '[{"question": "Le cumin est-il piquant?", "answer": "Non, le cumin n''est pas piquant. Il a un goût chaud et terreux mais sans piquant. Ne pas confondre avec le piment de Cayenne."}, {"question": "Cumin moulu ou en graines?", "answer": "Les graines entières gardent leur saveur plus longtemps et peuvent être grillées. Le cumin moulu est plus pratique pour une utilisation immédiate."}]'::jsonb,
  ARRAY['chaud', 'indien', 'mexicain', 'moyen-orient'],
  true
);

-- 2. CURCUMA
INSERT INTO spices (
  slug, name_fr, name_en, other_names,
  definition_fr, definition_en,
  origin, history_fr, history_en,
  taste_profile, usage_tips_fr, usage_tips_en,
  common_mistakes_fr, common_mistakes_en,
  used_with, benefits_fr, benefits_en,
  storage_fr, storage_en, substitutes,
  seo_title_fr, seo_title_en,
  seo_description_fr, seo_description_en,
  faq, categories, is_published
) VALUES (
  'curcuma',
  'Curcuma',
  'Turmeric',
  ARRAY['Safran des Indes', 'Curcuma longa'],
  'Le curcuma est une épice dorée au goût légèrement amer et poivré. Célèbre pour sa couleur jaune vif et ses propriétés anti-inflammatoires.',
  'Turmeric is a golden spice with a slightly bitter and peppery taste. Famous for its bright yellow color and anti-inflammatory properties.',
  ARRAY['Inde', 'Asie du Sud-Est'],
  'Utilisé depuis plus de 4000 ans en Inde, le curcuma est sacré dans la culture hindoue et utilisé en médecine ayurvédique.',
  'Used for over 4000 years in India, turmeric is sacred in Hindu culture and used in Ayurvedic medicine.',
  '{"intensity": 2, "spicy": 0, "bitterness": 2, "sweetness": 0, "notes_fr": ["terreux", "légèrement amer", "poivré", "musqué"], "notes_en": ["earthy", "slightly bitter", "peppery", "musky"]}'::jsonb,
  '<p><strong>Comment l''utiliser:</strong></p><ul><li>Toujours associer avec du poivre noir pour améliorer l''absorption</li><li>Ajouter un corps gras (huile, lait de coco) pour activer la curcumine</li><li>Utiliser avec parcimonie - colore tout!</li></ul>',
  '<p><strong>How to use:</strong></p><ul><li>Always pair with black pepper to improve absorption</li><li>Add a fat (oil, coconut milk) to activate curcumin</li><li>Use sparingly - it stains everything!</li></ul>',
  '<p><strong>Erreurs à éviter:</strong></p><ul><li>Attention aux taches - le curcuma colore les surfaces, vêtements et plastiques</li><li>Ne pas surdoser - goût amer si trop</li></ul>',
  '<p><strong>Mistakes to avoid:</strong></p><ul><li>Beware of stains - turmeric stains surfaces, clothes and plastics</li><li>Don''t overdo it - becomes bitter if too much</li></ul>',
  '{"meat": ["poulet", "agneau"], "fish": ["poisson blanc"], "vegetables": ["chou-fleur", "pommes de terre", "légumes-racines"], "grains": ["riz"], "bread": [], "desserts": [], "cheese": [], "soups": ["curry", "soupe de lentilles"]}'::jsonb,
  '<p>Puissant anti-inflammatoire naturel, antioxydant.</p>',
  '<p>Powerful natural anti-inflammatory, antioxidant.</p>',
  '<p>À l''abri de la lumière (perd sa couleur). 2-3 ans.</p>',
  '<p>Away from light (loses color). 2-3 years.</p>',
  ARRAY['safran', 'curry'],
  'Curcuma: L''Or de l''Inde | Guide et Bienfaits',
  'Turmeric: India''s Gold | Guide and Benefits',
  'Guide complet du curcuma: goût, bienfaits santé, utilisations. L''épice aux mille vertus pour vos curry et golden milk.',
  'Complete turmeric guide: taste, health benefits, uses. The spice with a thousand virtues for your curry and golden milk.',
  '[{"question": "Comment activer le curcuma?", "answer": "Le curcuma doit être combiné avec du poivre noir et un corps gras pour que la curcumine soit bien absorbée par l''organisme."}, {"question": "Le curcuma tache-t-il?", "answer": "Oui! Le curcuma est un colorant naturel puissant. Protégez vos surfaces et évitez les contenants en plastique blanc."}]'::jsonb,
  ARRAY['doux', 'indien', 'asiatique', 'santé'],
  true
);

-- 3. CANNELLE
INSERT INTO spices (
  slug, name_fr, name_en, other_names,
  definition_fr, definition_en,
  origin, history_fr, history_en,
  taste_profile, usage_tips_fr, usage_tips_en,
  common_mistakes_fr, common_mistakes_en,
  used_with, benefits_fr, benefits_en,
  storage_fr, storage_en, substitutes,
  seo_title_fr, seo_title_en,
  seo_description_fr, seo_description_en,
  faq, categories, is_published
) VALUES (
  'cannelle',
  'Cannelle',
  'Cinnamon',
  ARRAY['Cinnamomum verum', 'Cinnamomum cassia'],
  'La cannelle est une épice douce et chaude avec des notes sucrées et boisées. Indispensable en pâtisserie et dans les plats réconfortants.',
  'Cinnamon is a sweet and warm spice with sweet and woody notes. Essential in baking and comfort dishes.',
  ARRAY['Sri Lanka', 'Indonésie', 'Chine'],
  'La cannelle était l''une des premières épices commercialisées. Dans l''Antiquité, elle valait plus cher que l''or.',
  'Cinnamon was one of the first traded spices. In ancient times, it was worth more than gold.',
  '{"intensity": 3, "spicy": 0, "bitterness": 0, "sweetness": 4, "notes_fr": ["sucré", "boisé", "chaud", "vanillé"], "notes_en": ["sweet", "woody", "warm", "vanilla"]}'::jsonb,
  '<p><strong>Comment l''utiliser:</strong></p><ul><li>En bâton dans les boissons chaudes et mijotés</li><li>Moulue dans les pâtisseries et desserts</li><li>Excellent avec les pommes et les poires</li></ul>',
  '<p><strong>How to use:</strong></p><ul><li>As sticks in hot drinks and stews</li><li>Ground in pastries and desserts</li><li>Excellent with apples and pears</li></ul>',
  '<p><strong>Erreurs à éviter:</strong></p><ul><li>Ne pas confondre cannelle de Ceylan (vraie) et cassia (plus commune)</li><li>Attention au dosage - peut devenir écœurant</li></ul>',
  '<p><strong>Mistakes to avoid:</strong></p><ul><li>Don''t confuse Ceylon cinnamon (true) with cassia (more common)</li><li>Watch the dosage - can become cloying</li></ul>',
  '{"meat": ["agneau", "porc"], "fish": [], "vegetables": ["patates douces", "courges"], "grains": ["riz au lait", "gruau"], "bread": ["brioches", "pain aux raisins"], "desserts": ["tartes aux pommes", "biscuits", "crèmes"], "cheese": [], "soups": []}'::jsonb,
  '<p>Régule la glycémie, antibactérien naturel.</p>',
  '<p>Regulates blood sugar, natural antibacterial.</p>',
  '<p>Bâtons: 2-3 ans. Moulue: 6 mois. À l''abri de l''humidité.</p>',
  '<p>Sticks: 2-3 years. Ground: 6 months. Away from moisture.</p>',
  ARRAY['quatre-epices', 'muscade'],
  'Cannelle: L''Épice Douce par Excellence | Guide',
  'Cinnamon: The Sweet Spice | Complete Guide',
  'Guide complet de la cannelle: vraie cannelle vs cassia, utilisations sucrées et salées. Indispensable en pâtisserie!',
  'Complete cinnamon guide: true cinnamon vs cassia, sweet and savory uses. Essential in baking!',
  '[{"question": "Quelle différence entre cannelle de Ceylan et cassia?", "answer": "La cannelle de Ceylan (vraie cannelle) est plus douce et subtile. La cassia est plus forte et moins chère. Pour un usage quotidien, la cassia convient; pour la pâtisserie fine, préférez Ceylan."}, {"question": "La cannelle est-elle bonne pour la santé?", "answer": "Oui, en quantité modérée. Elle aide à réguler la glycémie et a des propriétés antibactériennes. Évitez les excès de cassia qui contient de la coumarine."}]'::jsonb,
  ARRAY['doux', 'sucré', 'pâtisserie'],
  true
);

-- 4. GINGEMBRE
INSERT INTO spices (
  slug, name_fr, name_en, other_names,
  definition_fr, definition_en,
  origin, history_fr, history_en,
  taste_profile, usage_tips_fr, usage_tips_en,
  common_mistakes_fr, common_mistakes_en,
  used_with, benefits_fr, benefits_en,
  storage_fr, storage_en, substitutes,
  seo_title_fr, seo_title_en,
  seo_description_fr, seo_description_en,
  faq, categories, is_published
) VALUES (
  'gingembre',
  'Gingembre',
  'Ginger',
  ARRAY['Zingiber officinale'],
  'Le gingembre est une épice vive et piquante avec des notes citronnées et poivrées. Utilisé frais, séché ou en poudre.',
  'Ginger is a lively and pungent spice with lemony and peppery notes. Used fresh, dried or powdered.',
  ARRAY['Asie du Sud-Est', 'Chine', 'Inde'],
  'Le gingembre est utilisé depuis plus de 5000 ans en médecine traditionnelle chinoise et ayurvédique.',
  'Ginger has been used for over 5000 years in traditional Chinese and Ayurvedic medicine.',
  '{"intensity": 4, "spicy": 3, "bitterness": 0, "sweetness": 1, "notes_fr": ["piquant", "citronné", "poivré", "frais"], "notes_en": ["pungent", "lemony", "peppery", "fresh"]}'::jsonb,
  '<p><strong>Comment l''utiliser:</strong></p><ul><li>Frais: râper ou émincer finement</li><li>En poudre: plus concentré, réduire la quantité</li><li>Marinade, sautés, boissons, desserts</li></ul>',
  '<p><strong>How to use:</strong></p><ul><li>Fresh: grate or slice thinly</li><li>Powdered: more concentrated, reduce quantity</li><li>Marinades, stir-fries, drinks, desserts</li></ul>',
  '<p><strong>Erreurs à éviter:</strong></p><ul><li>Le gingembre frais et en poudre ne s''équivalent pas (1 c. frais = 1/4 c. poudre)</li><li>Ne pas surchauffer - perd son piquant</li></ul>',
  '<p><strong>Mistakes to avoid:</strong></p><ul><li>Fresh and powdered ginger are not equivalent (1 tbsp fresh = 1/4 tsp powder)</li><li>Don''t overheat - loses its punch</li></ul>',
  '{"meat": ["poulet", "porc", "bœuf"], "fish": ["saumon", "crevettes", "thon"], "vegetables": ["carottes", "bok choy"], "grains": ["riz sauté"], "bread": ["pain d''épices"], "desserts": ["biscuits", "gâteaux"], "cheese": [], "soups": ["soupe miso", "bouillons"]}'::jsonb,
  '<p>Anti-nauséeux, anti-inflammatoire, aide à la digestion.</p>',
  '<p>Anti-nausea, anti-inflammatory, aids digestion.</p>',
  '<p>Frais: 3 semaines au frigo. Poudre: 2-3 ans.</p>',
  '<p>Fresh: 3 weeks in fridge. Powder: 2-3 years.</p>',
  ARRAY['galanga'],
  'Gingembre: L''Épice Vive et Piquante | Guide',
  'Ginger: The Lively Spice | Complete Guide',
  'Guide complet du gingembre: frais vs en poudre, bienfaits santé, recettes. Indispensable en cuisine asiatique!',
  'Complete ginger guide: fresh vs powder, health benefits, recipes. Essential in Asian cuisine!',
  '[{"question": "Gingembre frais ou en poudre?", "answer": "Le gingembre frais a un goût plus vif et citronné. La poudre est plus concentrée et chaude. Utilisez frais pour les sautés, poudre pour les pâtisseries."}, {"question": "Le gingembre aide-t-il contre les nausées?", "answer": "Oui! Le gingembre est reconnu pour ses propriétés anti-nauséeuses, efficace contre le mal des transports et les nausées de grossesse (avec avis médical)."}]'::jsonb,
  ARRAY['piquant', 'asiatique', 'santé', 'chaud'],
  true
);

-- 5. CORIANDRE (graines)
INSERT INTO spices (
  slug, name_fr, name_en, other_names,
  definition_fr, definition_en,
  origin, history_fr, history_en,
  taste_profile, usage_tips_fr, usage_tips_en,
  common_mistakes_fr, common_mistakes_en,
  used_with, benefits_fr, benefits_en,
  storage_fr, storage_en, substitutes,
  seo_title_fr, seo_title_en,
  seo_description_fr, seo_description_en,
  faq, categories, is_published
) VALUES (
  'coriandre',
  'Coriandre (graines)',
  'Coriander Seeds',
  ARRAY['Coriandrum sativum'],
  'Les graines de coriandre ont un goût doux, citronné et légèrement sucré, très différent des feuilles fraîches.',
  'Coriander seeds have a mild, lemony and slightly sweet taste, very different from fresh leaves.',
  ARRAY['Méditerranée', 'Moyen-Orient', 'Asie'],
  'L''une des plus anciennes épices connues, mentionnée dans la Bible et trouvée dans les tombes égyptiennes.',
  'One of the oldest known spices, mentioned in the Bible and found in Egyptian tombs.',
  '{"intensity": 2, "spicy": 0, "bitterness": 0, "sweetness": 1, "notes_fr": ["citronné", "doux", "floral", "légèrement sucré"], "notes_en": ["lemony", "mild", "floral", "slightly sweet"]}'::jsonb,
  '<p><strong>Comment l''utiliser:</strong></p><ul><li>Griller légèrement avant de moudre</li><li>Excellent dans les marinades et currys</li><li>S''associe bien avec le cumin</li></ul>',
  '<p><strong>How to use:</strong></p><ul><li>Lightly toast before grinding</li><li>Excellent in marinades and curries</li><li>Pairs well with cumin</li></ul>',
  '<p><strong>Erreurs à éviter:</strong></p><ul><li>Ne pas confondre avec les feuilles fraîches (goût très différent)</li><li>Graines entières ne libèrent pas bien leur saveur sans être écrasées</li></ul>',
  '<p><strong>Mistakes to avoid:</strong></p><ul><li>Don''t confuse with fresh leaves (very different taste)</li><li>Whole seeds don''t release flavor well without crushing</li></ul>',
  '{"meat": ["poulet", "agneau", "porc"], "fish": ["poisson blanc"], "vegetables": ["carottes", "pommes de terre"], "grains": ["riz", "couscous"], "bread": ["pain"], "desserts": [], "cheese": [], "soups": ["soupe de lentilles", "curry"]}'::jsonb,
  '<p>Aide à la digestion, propriétés antioxydantes.</p>',
  '<p>Aids digestion, antioxidant properties.</p>',
  '<p>Graines entières: 3-4 ans. Moulue: 6 mois.</p>',
  '<p>Whole seeds: 3-4 years. Ground: 6 months.</p>',
  ARRAY['cumin', 'carvi'],
  'Coriandre en Graines: Épice Douce et Citronnée',
  'Coriander Seeds: Mild Lemony Spice',
  'Guide des graines de coriandre: goût citronné, utilisations en curry et marinades. Ne pas confondre avec la coriandre fraîche!',
  'Coriander seeds guide: lemony taste, uses in curry and marinades. Not to be confused with fresh cilantro!',
  '[{"question": "Graines de coriandre vs feuilles fraîches?", "answer": "Goût complètement différent! Les graines sont douces et citronnées. Les feuilles (cilantro) ont un goût plus herbacé que certains trouvent savonneux."}, {"question": "Avec quelles épices associer la coriandre?", "answer": "Le cumin est le partenaire classique. Aussi excellent avec le gingembre, le curcuma et le fenouil pour créer des mélanges d''épices."}]'::jsonb,
  ARRAY['doux', 'indien', 'moyen-orient', 'méditerranéen'],
  true
);
